"""ActionSpec declarations for cheminformatics."""

from __future__ import annotations

from .._spec_builders import action as _action


ACTION_SPECS = (
    _action(
            "calculate_molecular_descriptors",
            "cheminformatics",
            "Calculate an explicitly selected set of graph-based molecular descriptors without generating coordinates or running electronic structure.",
            "MolecularDescriptorResult",
            ("rdkit",),
            ("molecule",),
            input_description="molecule: SMILES, molecular structure, or compatible Artifact",
        ),
    _action(
            "calculate_molecular_fingerprint",
            "cheminformatics",
            "Calculate one explicitly selected molecular fingerprint representation.",
            "MolecularFingerprint",
            ("rdkit",),
            ("molecule",),
            input_description="molecule: SMILES or molecular structure",
        ),
    _action(
            "calculate_molecular_similarity",
            "cheminformatics",
            "Calculate one similarity value between two molecules using an explicit fingerprint and metric.",
            "MolecularSimilarityResult",
            ("rdkit",),
            ("molecule_a", "molecule_b"),
            input_description="two molecular representations plus explicit fingerprint and similarity metric",
        ),
    _action(
            "search_local_substructures",
            "cheminformatics",
            "Find atom-index matches for an explicit SMARTS or SMILES query in one supplied molecule.",
            "SubstructureMatchResult",
            ("rdkit",),
            ("molecule", "query"),
            input_description="target molecule and explicit SMARTS/SMILES query",
        ),
    _action(
            "enumerate_tautomers",
            "cheminformatics",
            "Enumerate bounded tautomeric forms without selecting a preferred tautomer for the agent.",
            "MoleculeCollection",
            ("rdkit",),
            ("molecule",),
            input_description="one molecular representation and an explicit enumeration bound",
        ),
    _action(
            "enumerate_stereoisomers",
            "cheminformatics",
            "Enumerate bounded stereoisomers under explicit uniqueness and assignment rules.",
            "MoleculeCollection",
            ("rdkit",),
            ("molecule",),
            input_description="one molecular representation and explicit stereoisomer enumeration settings",
        ),
    _action(
            "discover_sparse_symbolic_descriptor",
            "cheminformatics",
            "Fit one single-task SISSO regression model from an explicit CSV train/validation split without choosing columns, units, operators, complexity, sparsification, or ranking metrics for the agent.",
            "SparseSymbolicDescriptorResult",
            ("sisso",),
            ("dataset",),
            input_description="CSV table plus explicit sample-ID, target and feature columns; disjoint training/validation sample IDs; feature-unit groups; and complete SISSO search controls",
        ),
    _action(
            "evaluate_sparse_symbolic_descriptor",
            "cheminformatics",
            "Evaluate one existing SISSO regression model on an explicitly supplied CSV dataset using the matching official SISSO_predict utility.",
            "SparseSymbolicDescriptorEvaluation",
            ("sisso",),
            ("model_output", "dataset"),
            input_description="SISSO.out, CSV table, explicit sample-ID/target/feature columns, model dimension, and bounded returned predictions",
        ),
    _action(
            "summarize_sparse_symbolic_descriptor_results",
            "cheminformatics",
            "Parse an existing SISSO model and optional SISSO_predict result into bounded structured statistics without fitting or evaluating a model.",
            "SparseSymbolicDescriptorSummary",
            ("sisso",),
            ("model_output",),
            ("prediction_output",),
            input_description="SISSO.out plus optional predict_Y.out and an explicit prediction-record bound",
            selection_policy="internal_deterministic",
        ),
    _action(
            "fit_symbolic_regression_baseline",
            "cheminformatics",
            "Fit one gplearn symbolic-regression baseline from an explicit CSV train/validation split and fully specified genetic-programming controls.",
            "SymbolicRegressionResult",
            ("gplearn",),
            ("dataset",),
            input_description="CSV table, explicit sample-ID/target/feature columns, disjoint train/validation IDs, function set, metric, and complete genetic-programming controls",
        ),
    _action(
            "assess_symbolic_regression_seed_stability",
            "cheminformatics",
            "Repeat one fixed gplearn symbolic-regression specification over explicit random seeds and report equation and held-out-metric stability.",
            "SymbolicRegressionStabilityResult",
            ("gplearn",),
            ("dataset",),
            input_description="CSV table and one fixed symbolic-regression specification plus an explicit bounded list of random seeds",
        ),
    _action(
            "summarize_symbolic_regression_results",
            "cheminformatics",
            "Parse a JSON result produced by a gplearn Action into bounded structured statistics without fitting or loading a serialized Python model.",
            "SymbolicRegressionSummary",
            ("gplearn",),
            ("results_file",),
            input_description="gplearn Action JSON result and an explicit returned-prediction bound",
            selection_policy="internal_deterministic",
        ),
)
