"""ActionSpec declarations for data_sources."""

from __future__ import annotations

from .._spec_builders import action as _action


ACTION_SPECS = (
    _action(
            "search_compounds",
            "data_sources",
            "Search PubChem compound records by an explicit identifier and namespace.",
            "CompoundRecords",
            ("pubchem",),
            ("query",),
            input_description="query string plus namespace/max_records settings",
            data_action=True,
            requires_network=True,
        ),
    _action(
            "resolve_chemical_identity",
            "data_sources",
            "Resolve one explicit compound identifier to a bounded ChemicalIdentity record through PubChem.",
            "ChemicalIdentity",
            ("pubchem",),
            ("query",),
            input_description="query={identifier, namespace: name|cid|smiles|inchi|inchikey}",
            data_action=True,
            requires_network=True,
        ),
    _action(
            "retrieve_compound_properties",
            "data_sources",
            "Retrieve an explicitly selected bounded property set for matching PubChem compounds.",
            "CompoundPropertyRecords",
            ("pubchem",),
            ("query",),
            input_description="query={identifier, namespace}; action_settings.properties selects allowed fields",
            data_action=True,
            requires_network=True,
        ),
    _action(
            "retrieve_compound_structure",
            "data_sources",
            "Retrieve bounded PubChem 2D or 3D coordinate records while leaving coordinate dimensionality and explicit-hydrogen handling to the agent.",
            "StructureCollection",
            ("pubchem",),
            ("query",),
            input_description="query={identifier, namespace}; explicit record_type and hydrogen policy select the returned coordinate representation",
            data_action=True,
            requires_network=True,
        ),
    _action(
            "search_similar_compounds",
            "data_sources",
            "Run one bounded PubChem 2D similarity search from an explicit structure identifier.",
            "CompoundRecords",
            ("pubchem",),
            ("query",),
            input_description="query={identifier, namespace: cid|smiles|inchi} plus threshold/max_records",
            data_action=True,
            requires_network=True,
        ),
    _action(
            "search_substructures",
            "data_sources",
            "Run one bounded PubChem substructure search from an explicit SMILES, SMARTS, InChI, or CID query.",
            "CompoundRecords",
            ("pubchem",),
            ("query",),
            input_description="query={identifier, namespace: cid|smiles|smarts|inchi} plus explicit matching controls",
            data_action=True,
            requires_network=True,
        ),
    _action(
            "search_protein_structures",
            "data_sources",
            "Search or retrieve RCSB PDB structure records using explicit identifiers or query terms.",
            "ProteinStructureRecords",
            ("rcsb_pdb",),
            ("query",),
            input_description="PDB id or search query",
            data_action=True,
            requires_network=True,
        ),
    _action(
            "search_materials",
            "data_sources",
            "Search Materials Project records by material id, formula, or explicit query fields.",
            "MaterialRecords",
            ("materials_project",),
            ("query",),
            input_description="material id, formula, or structured query",
            data_action=True,
            requires_network=True,
        ),
    _action(
            "search_catalysis_records",
            "data_sources",
            "Search Catalysis-Hub reaction records using explicit reactant/product filters.",
            "CatalysisRecords",
            ("catalysis_hub",),
            ("query",),
            input_description="structured reactant/product query",
            data_action=True,
            requires_network=True,
        ),
    _action(
            "lookup_nist_webbook_species",
            "data_sources",
            "Look up one bounded NIST Chemistry WebBook species query by explicit CAS number, exact name, or exact formula through the official CGI interface.",
            "NISTWebBookSpeciesRecords",
            ("nist_webbook",),
            ("query",),
            input_description=(
                "query={identifier, namespace: cas|name|formula}; formula queries also "
                "require explicit match_isotopes and exclude_ions booleans"
            ),
            data_action=True,
            requires_network=True,
        ),
    _action(
            "retrieve_crystal_structure",
            "data_sources",
            "Retrieve one explicitly identified CCDC/CSD crystal record from a licensed CCDC API or an Agent-supplied CIF export.",
            "CrystalStructureRecord",
            ("ccdc",),
            ("query",),
            input_description="query={record_id, optional cif_path}; settings select component and hydrogen policies",
            data_action=True,
            requires_network=False,
        ),
)
