"""ActionSpec declarations for periodic_and_phonons."""

from __future__ import annotations

from .._spec_builders import action as _action


ACTION_SPECS = (
    _action(
            "calculate_quasiparticle_corrections",
            "periodic_and_phonons",
            "Run one explicit Yambo quasiparticle calculation from an existing SAVE database and native input file, then return bounded state corrections.",
            "QuasiparticleCorrectionResult",
            ("yambo",),
            ("save_directory", "input_file"),
            input_description="compatible Yambo SAVE database and explicit GW input file",
        ),
    _action(
            "calculate_bse_optical_spectrum",
            "periodic_and_phonons",
            "Run one explicit Yambo Bethe-Salpeter calculation from existing databases and return a bounded optical spectrum.",
            "OpticalSpectrumResult",
            ("yambo",),
            ("save_directory", "input_file"),
            ("restart_directories",),
            input_description="compatible Yambo SAVE database, explicit BSE input, and optional named screening/restart databases",
        ),
    _action(
            "generate_crystal_structure_candidates",
            "periodic_and_phonons",
            "Generate a bounded set of random crystal candidates from one explicit AIRSS buildcell seed file without relaxing or ranking them.",
            "CrystalStructureCandidateSet",
            ("airss",),
            ("seed_file",),
            input_description="annotated CASTEP .cell seed file containing the composition and AIRSS build constraints",
        ),
    _action(
            "convert_crystal_structure_format",
            "periodic_and_phonons",
            "Convert one existing crystal-structure file between two explicitly selected AIRSS cabal formats.",
            "CrystalStructureFile",
            ("airss",),
            ("structure_file",),
            input_description="existing crystal-structure file plus explicit input and output format identifiers",
        ),
    _action(
            "generate_vasp_kpoint_mesh",
            "periodic_and_phonons",
            "Generate one VASP KPOINTS mesh from an existing POSCAR using an explicit reciprocal-space resolution and centering scheme.",
            "KPointMesh",
            ("vaspkit",),
            ("structure_file",),
            input_description="VASP POSCAR/CONTCAR plus explicit reciprocal-space resolution and Gamma or Monkhorst-Pack centering",
        ),
    _action(
            "extract_vasp_band_gap",
            "periodic_and_phonons",
            "Extract band-gap character, edge eigenvalues, band indices and k-point locations from one complete existing VASP electronic-result set.",
            "ElectronicBandGapResult",
            ("vaspkit",),
            ("structure_file", "incar_file", "eigenvalue_file", "dos_file"),
            ("outcar_file",),
            input_description="matching POSCAR, INCAR, EIGENVAL and DOSCAR files plus optional OUTCAR and explicit Fermi-reference policy",
        ),
    _action(
            "calculate_adsorption_energy",
            "periodic_and_phonons",
            "Combine explicitly supplied adsorbed-system, clean-surface, and reference-species energies into an adsorption energy without selecting reference states or running electronic-structure calculations.",
            "AdsorptionEnergyResult",
            ("internal_periodic_analysis",),
            ("adsorbed_system_energy", "clean_surface_energy", "reference_species"),
            input_description="aligned total energies plus explicit reference-species stoichiometric coefficients",
            selection_policy="internal_deterministic",
        ),
    _action(
            "construct_pressure_enthalpy_phase_diagram",
            "periodic_and_phonons",
            "Determine stable phases and linearly interpolated transition pressures from explicit phase enthalpies evaluated on one common pressure grid.",
            "PressureEnthalpyPhaseDiagramResult",
            ("internal_periodic_analysis",),
            ("phase_records",),
            input_description="phase-labeled pressure/enthalpy records on an identical pressure grid",
            selection_policy="internal_deterministic",
        ),
    _action(
            "assess_phonon_stability",
            "periodic_and_phonons",
            "Assess dynamical stability and Gamma-point acoustic-mode quality from explicitly supplied q-point phonon frequencies and tolerances.",
            "PhononStabilityAssessment",
            ("internal_periodic_analysis",),
            ("phonon_records",),
            input_description="q-point vectors and aligned phonon-frequency lists from an existing dispersion calculation",
            selection_policy="internal_deterministic",
        ),
    _action(
            "fit_effective_force_constants",
            "periodic_and_phonons",
            "Fit temperature-dependent effective force constants from an explicit aligned supercell simulation dataset.",
            "EffectiveForceConstantModel",
            ("tdep",),
            ("unit_cell_file", "supercell_file", "simulation_file"),
            ("loto_splitting_file",),
            input_description="TDEP unit/supercell POSCAR files and packed simulation positions, forces, energies, and stresses",
        ),
    _action(
            "generate_thermal_displacement_configurations",
            "periodic_and_phonons",
            "Sample a bounded set of thermally displaced supercells from an explicit harmonic model or explicit Debye/frequency initialization.",
            "ThermalDisplacementConfigurationSet",
            ("tdep",),
            ("unit_cell_file", "supercell_file"),
            ("second_order_force_constants_file",),
            input_description="TDEP unit/supercell files plus an explicit force-constant or model-initialization source",
        ),
    _action(
            "calculate_temperature_dependent_phonon_dispersion",
            "periodic_and_phonons",
            "Calculate phonon bands from one explicit TDEP effective second-order force-constant model.",
            "PhononDispersion",
            ("tdep",),
            ("unit_cell_file", "second_order_force_constants_file"),
            ("q_path_file", "third_order_force_constants_file"),
            input_description="TDEP unit-cell and fitted force-constant files plus an optional explicit q-point path",
        ),
    _action(
            "calculate_periodic_energy",
            "periodic_and_phonons",
            "Calculate one periodic-system energy with the explicitly selected electronic-structure backend.",
            "EnergyResult",
            ("quantum_espresso", "cp2k", "siesta", "dftbplus", "abinit", "vasp", "gpaw", "nequip", "allegro", "deepmd"),
            ("structure",),
            input_description="periodic AtomicStructure with cell and PBC",
            batch_safe=True,
        ),
    _action(
            "calculate_periodic_forces",
            "periodic_and_phonons",
            "Calculate periodic atomic forces for one structure or aligned displaced-structure batch.",
            "ForceResult",
            ("quantum_espresso", "cp2k", "siesta", "dftbplus", "abinit", "vasp", "gpaw", "nequip", "allegro", "deepmd"),
            ("structure",),
            input_description="periodic AtomicStructure or homogeneous structure batch",
        ),
    _action(
            "calculate_periodic_stress",
            "periodic_and_phonons",
            "Calculate one periodic stress tensor without relaxing the structure.",
            "StressResult",
            ("quantum_espresso", "cp2k", "abinit", "vasp", "gpaw", "nequip", "allegro", "deepmd"),
            ("structure",),
            input_description="periodic AtomicStructure",
        ),
    _action(
            "relax_periodic_structure",
            "periodic_and_phonons",
            "Relax a periodic structure under explicit atomic/cell constraints.",
            "AtomicStructure",
            ("quantum_espresso", "cp2k", "siesta", "dftbplus", "abinit", "vasp", "gpaw", "nequip", "allegro", "deepmd"),
            ("structure",),
            input_description="periodic AtomicStructure plus explicit relaxation controls",
        ),
    _action(
            "calculate_electronic_band_structure",
            "periodic_and_phonons",
            "Calculate electronic eigenvalue bands along one explicit reciprocal-space path from an existing converged periodic ground-state restart.",
            "ElectronicBandStructureResult",
            ("gpaw",),
            ("ground_state",),
            input_description="converged GPAW ground-state restart Artifact plus an explicit high-symmetry path, sampling, and band count",
        ),
    _action(
            "calculate_density_of_states",
            "periodic_and_phonons",
            "Calculate a total electronic density of states on an explicit energy grid from an existing converged periodic ground-state restart.",
            "DensityOfStatesResult",
            ("gpaw",),
            ("ground_state",),
            input_description="converged GPAW ground-state restart Artifact plus explicit energy range, grid, broadening, spin, and reference",
        ),
    _action(
            "calculate_projected_density_of_states",
            "periodic_and_phonons",
            "Calculate or extract explicitly requested atom/orbital projected electronic densities of states from an existing compatible periodic electronic-state artifact.",
            "ProjectedDensityOfStatesResult",
            ("gpaw", "lobster"),
            ("projections",),
            ("ground_state", "dos_file", "structure_file"),
            input_description="typed atom/orbital projections plus either a GPAW restart or LOBSTER DOSCAR/structure artifacts",
        ),
    _action(
            "analyze_periodic_bonding",
            "periodic_and_phonons",
            "Extract explicitly selected integrated and optional energy-resolved COHP, COOP, or COBI bonding information from existing LOBSTER outputs.",
            "PeriodicBondingResult",
            ("lobster",),
            ("integrated_bond_list",),
            ("bond_curve_file",),
            input_description="LOBSTER ICOHPLIST/ICOOPLIST/ICOBILIST and optional matching COHPCAR/COOPCAR/COBICAR Artifact",
        ),
    _action(
            "calculate_charge_spilling",
            "periodic_and_phonons",
            "Assess LOBSTER wavefunction-projection charge/total spilling against explicit acceptance thresholds from an existing lobsterout file.",
            "ProjectionQualityResult",
            ("lobster",),
            ("lobster_output",),
            input_description="existing LOBSTER lobsterout Artifact and explicit charge/total spilling thresholds",
        ),
    _action(
            "generate_displaced_supercells",
            "periodic_and_phonons",
            "Generate a displacement set from an explicit supercell matrix and displacement amplitude.",
            "DisplacementSet",
            ("phonopy", "phono3py"),
            ("structure",),
            input_description="periodic AtomicStructure",
        ),
    _action(
            "assemble_force_constants",
            "periodic_and_phonons",
            "Assemble force constants only from a supplied displacement set and aligned forces.",
            "ForceConstants",
            ("phonopy", "phono3py"),
            ("displacement_set", "force_set"),
            input_description="DisplacementSet and ForceSet Artifacts",
        ),
    _action(
            "calculate_phonon_dispersion",
            "periodic_and_phonons",
            "Calculate a phonon dispersion from existing force constants and an explicit q-point path.",
            "PhononDispersion",
            ("phonopy", "phono3py"),
            ("force_constants", "structure"),
            input_description="ForceConstants, structure, and q_path setting",
        ),
    _action(
            "calculate_phonon_density_of_states",
            "periodic_and_phonons",
            "Calculate a phonon density of states from existing force constants and an explicit q mesh.",
            "PhononDensityOfStates",
            ("phonopy", "phono3py"),
            ("force_constants", "structure"),
            input_description="ForceConstants, structure, and q_mesh setting",
        ),
    _action(
            "calculate_harmonic_thermodynamics",
            "periodic_and_phonons",
            "Calculate harmonic free energy, entropy, and constant-volume heat capacity at explicitly supplied temperatures.",
            "HarmonicThermodynamicsResult",
            ("phonopy", "phono3py"),
            ("force_constants", "structure"),
            input_description="second-order ForceConstants, matching structure, q mesh, and explicit temperature list",
        ),
    _action(
            "calculate_phonon_group_velocities",
            "periodic_and_phonons",
            "Calculate mode-resolved phonon group-velocity vectors along an explicitly supplied q-point path.",
            "PhononGroupVelocityResult",
            ("phonopy", "phono3py"),
            ("force_constants", "structure"),
            input_description="second-order ForceConstants, matching structure, and explicit q_path",
        ),
    _action(
            "calculate_lattice_thermal_conductivity",
            "periodic_and_phonons",
            "Calculate the lattice thermal-conductivity tensor from explicit second-/third-order force constants or a complete native BTE model under Agent-selected solution and scattering settings.",
            "LatticeThermalConductivityResult",
            ("phono3py", "shengbte"),
            (),
            (
                "second_order_force_constants", "third_order_force_constants", "structure",
                "control_file", "second_order_force_constants_file",
                "third_order_force_constants_file", "born_file", "companion_files",
            ),
            input_description=(
                "Phono3py fc2/fc3 Artifacts plus structure, or explicit ShengBTE CONTROL/"
                "FORCE_CONSTANTS files and optional BORN/companion files"
            ),
        ),
)
