from pathlib import Path
import json
from ase.build import nanotube
from ase.io import write
from ase import Atoms
B=Path(__file__).resolve().parent;O=B/'prepared_inputs'
def dump(p,x):p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(x,indent=2)+'\n')
p='paper_94b0a8ae694590ea';d=O/p;d.mkdir(exist_ok=True)
a=nanotube(10,10,length=12,bond=1.42);a.center(vacuum=18,axis=(0,1));a.pbc=(False,False,True)
write(d/'benchmark_10_10_12repeat.extxyz',a)
dump(d/'tube_definition.json',{'origin':'Benchmark-defined ideal periodic model, NOT a source measured chirality or source CIF','n':10,'m':10,'primitive_repeats':12,'carbon_atoms':len(a),'bond_start_angstrom':1.42,'cell_angstrom':a.cell.array.tolist(),'periodic_axes':[False,False,True],'coverage':'One intact neutral source molecule per 12 primitive repeats; same for all three molecules','model_limit':'Source XFS22 SWCNT reports diameter 1–2 nm and length 5–30 um, with no single chirality; conclusions are conditional on (10,10).','mapping':'Tube indices 1..480 from extxyz; append molecule atoms in original XYZ row order. Repeat control maps cell0 and cell1 explicitly.','controls':{'length_fixed_coverage':'24 repeats with two mapped adsorbates; compare per-molecule energy and work function at same density','dilution_optional':'24 repeats with one adsorbate changes coverage and is not a size-only control','vacuum':'Increase transverse vacuum from 18 to 24 angstrom per side; test radial electrostatic plateau','kpoints':'Converge reciprocal sampling along tube at equal reciprocal spacing between supercells','poses':'At least two independent pi-face/axial orientations per molecule; initially place nearest heavy atoms 3.2 angstrom outside tube surface, then relax'}})
p='paper_eda19e7c8edd4b39';d=O/p;d.mkdir(exist_ok=True)
a=Atoms('NiAl',scaled_positions=[[0,0,0],[.5,.5,.5]],cell=[2.89]*3,pbc=True);write(d/'benchmark_B2_start.extxyz',a)
b=Atoms('AlNi3',scaled_positions=[[0,0,0],[0,.5,.5],[.5,0,.5],[.5,.5,0]],cell=[3.57]*3,pbc=True);write(d/'benchmark_L12_start.extxyz',b)
dump(d/'lattice_and_surface_definition.json',{'origin':'Benchmark ideal crystal prototypes, not retrieved source CIF or relaxed answers','B2':{'basis':[{'element':'Ni','fractional':[0,0,0]},{'element':'Al','fractional':[.5,.5,.5]}],'a_start_angstrom':2.89},'L12_Ni3Al':{'basis':[{'element':'Al','fractional':[0,0,0]},{'element':'Ni','fractional':[0,.5,.5]},{'element':'Ni','fractional':[.5,0,.5]},{'element':'Ni','fractional':[.5,.5,0]}],'a_start_angstrom':3.57,'note':'Lattice guess only; optimize independently'},'reservoirs':{'Ni':'ferromagnetic fcc Ni conventional lattice start 3.52 angstrom','Al':'fcc Al conventional lattice start 4.05 angstrom','fcc_basis':[[0,0,0],[0,.5,.5],[.5,0,.5],[.5,.5,0]]},'bulk_controls':{'baseline_supercell':[2,2,2],'larger_supercell':[3,3,3],'vacancy_sites':['remove Ni basis0','remove Al basis1'],'identity':'Record each atom as (ix,iy,iz,basis) before deletion'},'slabs':{'orientations':[[1,0,0],[1,1,0]],'surface_supercell':[2,2],'baseline_layers':7,'thicker_layers':9,'vacuum_start_angstrom':15,'vacuum_control_angstrom':20,'100_terminations':['Ni','Al'],'110_termination':'mixed stoichiometric','mapping':'Use bulk integer cell/basis labels plus layer index. Archive exact generated slabs and count every atom.','symmetry':'Use inversion-equivalent two-face symmetric slabs where possible. Nonstoichiometric symmetric (100) terminations require chemical potentials. For asymmetric slabs account for two inequivalent surfaces and dipole correction; never assign a single surface energy from their sum.','relaxation':'Hold central layer bulk-like; relax outer layers; converge thickness before interpreting surface energy.'},'exchange':'For each termination exchange a surface Ni with a central-layer Al and a surface Al with central-layer Ni when each species is present; preserve composition and report signed E_exchanged-E_clean. Absence of species in top plane is handled by topmost layer containing that species, reported explicitly.','transfer':'Remove one species from a separate bulk cell and add it to a slab at candidate top/bridge/hollow sites; sum energies bulk-vacancy + slab-adatom - pristine-bulk - pristine-slab. Same species/atom count overall; no reservoirs needed for this balanced cycle.','phase_scope':'Compare L12 Ni3Al bulk grand potential with B2 under the same reservoirs. This is a phase thermodynamic competitor, not a modeled coherent precipitate/interface.'})
