"""ActionSpec declarations for periodic_and_phonons."""

from __future__ import annotations

from .._spec_builders import action as _action


ACTION_SPECS = (
    _action(
            "calculate_periodic_energy",
            "periodic_and_phonons",
            "Calculate one periodic-system energy with the explicitly selected electronic-structure backend.",
            "EnergyResult",
            ("quantum_espresso", "cp2k", "siesta", "dftbplus", "abinit", "vasp", "gpaw", "nequip", "allegro", "deepmd"),
            ("structure",),
            input_description="periodic AtomicStructure with cell and PBC",
        ),
    _action(
            "calculate_periodic_forces",
            "periodic_and_phonons",
            "Calculate periodic atomic forces for one structure or aligned displaced-structure batch.",
            "ForceResult",
            ("quantum_espresso", "cp2k", "siesta", "dftbplus", "abinit", "vasp", "gpaw", "nequip", "allegro", "deepmd"),
            ("structure",),
            input_description="periodic AtomicStructure or homogeneous structure batch",
        ),
    _action(
            "calculate_periodic_stress",
            "periodic_and_phonons",
            "Calculate one periodic stress tensor without relaxing the structure.",
            "StressResult",
            ("quantum_espresso", "cp2k", "abinit", "vasp", "gpaw", "nequip", "allegro", "deepmd"),
            ("structure",),
            input_description="periodic AtomicStructure",
        ),
    _action(
            "relax_periodic_structure",
            "periodic_and_phonons",
            "Relax a periodic structure under explicit atomic/cell constraints.",
            "AtomicStructure",
            ("quantum_espresso", "cp2k", "siesta", "dftbplus", "abinit", "vasp", "gpaw", "nequip", "allegro", "deepmd"),
            ("structure",),
            input_description="periodic AtomicStructure plus explicit relaxation controls",
        ),
    _action(
            "calculate_electronic_band_structure",
            "periodic_and_phonons",
            "Calculate electronic eigenvalue bands along one explicit reciprocal-space path from an existing converged periodic ground-state restart.",
            "ElectronicBandStructureResult",
            ("gpaw",),
            ("ground_state",),
            input_description="converged GPAW ground-state restart Artifact plus an explicit high-symmetry path, sampling, and band count",
        ),
    _action(
            "calculate_density_of_states",
            "periodic_and_phonons",
            "Calculate a total electronic density of states on an explicit energy grid from an existing converged periodic ground-state restart.",
            "DensityOfStatesResult",
            ("gpaw",),
            ("ground_state",),
            input_description="converged GPAW ground-state restart Artifact plus explicit energy range, grid, broadening, spin, and reference",
        ),
    _action(
            "calculate_projected_density_of_states",
            "periodic_and_phonons",
            "Calculate or extract explicitly requested atom/orbital projected electronic densities of states from an existing compatible periodic electronic-state artifact.",
            "ProjectedDensityOfStatesResult",
            ("gpaw", "lobster"),
            ("projections",),
            ("ground_state", "dos_file", "structure_file"),
            input_description="typed atom/orbital projections plus either a GPAW restart or LOBSTER DOSCAR/structure artifacts",
        ),
    _action(
            "analyze_periodic_bonding",
            "periodic_and_phonons",
            "Extract explicitly selected integrated and optional energy-resolved COHP, COOP, or COBI bonding information from existing LOBSTER outputs.",
            "PeriodicBondingResult",
            ("lobster",),
            ("integrated_bond_list",),
            ("bond_curve_file",),
            input_description="LOBSTER ICOHPLIST/ICOOPLIST/ICOBILIST and optional matching COHPCAR/COOPCAR/COBICAR Artifact",
        ),
    _action(
            "calculate_charge_spilling",
            "periodic_and_phonons",
            "Assess LOBSTER wavefunction-projection charge/total spilling against explicit acceptance thresholds from an existing lobsterout file.",
            "ProjectionQualityResult",
            ("lobster",),
            ("lobster_output",),
            input_description="existing LOBSTER lobsterout Artifact and explicit charge/total spilling thresholds",
        ),
    _action(
            "generate_displaced_supercells",
            "periodic_and_phonons",
            "Generate a displacement set from an explicit supercell matrix and displacement amplitude.",
            "DisplacementSet",
            ("phonopy", "phono3py"),
            ("structure",),
            input_description="periodic AtomicStructure",
        ),
    _action(
            "assemble_force_constants",
            "periodic_and_phonons",
            "Assemble force constants only from a supplied displacement set and aligned forces.",
            "ForceConstants",
            ("phonopy", "phono3py"),
            ("displacement_set", "force_set"),
            input_description="DisplacementSet and ForceSet Artifacts",
        ),
    _action(
            "calculate_phonon_dispersion",
            "periodic_and_phonons",
            "Calculate a phonon dispersion from existing force constants and an explicit q-point path.",
            "PhononDispersion",
            ("phonopy", "phono3py"),
            ("force_constants", "structure"),
            input_description="ForceConstants, structure, and q_path setting",
        ),
    _action(
            "calculate_phonon_density_of_states",
            "periodic_and_phonons",
            "Calculate a phonon density of states from existing force constants and an explicit q mesh.",
            "PhononDensityOfStates",
            ("phonopy", "phono3py"),
            ("force_constants", "structure"),
            input_description="ForceConstants, structure, and q_mesh setting",
        ),
    _action(
            "calculate_harmonic_thermodynamics",
            "periodic_and_phonons",
            "Calculate harmonic free energy, entropy, and constant-volume heat capacity at explicitly supplied temperatures.",
            "HarmonicThermodynamicsResult",
            ("phonopy", "phono3py"),
            ("force_constants", "structure"),
            input_description="second-order ForceConstants, matching structure, q mesh, and explicit temperature list",
        ),
    _action(
            "calculate_phonon_group_velocities",
            "periodic_and_phonons",
            "Calculate mode-resolved phonon group-velocity vectors along an explicitly supplied q-point path.",
            "PhononGroupVelocityResult",
            ("phonopy", "phono3py"),
            ("force_constants", "structure"),
            input_description="second-order ForceConstants, matching structure, and explicit q_path",
        ),
    _action(
            "calculate_lattice_thermal_conductivity",
            "periodic_and_phonons",
            "Calculate the lattice thermal-conductivity tensor from explicit second-/third-order force constants or a complete native BTE model under Agent-selected solution and scattering settings.",
            "LatticeThermalConductivityResult",
            ("phono3py", "shengbte"),
            (),
            (
                "second_order_force_constants", "third_order_force_constants", "structure",
                "control_file", "second_order_force_constants_file",
                "third_order_force_constants_file", "born_file", "companion_files",
            ),
            input_description=(
                "Phono3py fc2/fc3 Artifacts plus structure, or explicit ShengBTE CONTROL/"
                "FORCE_CONSTANTS files and optional BORN/companion files"
            ),
        ),
)
