"""Source extraction / identity checks only. No scientific engine computations."""
from pathlib import Path
import json,re,hashlib,collections,requests,zipfile,xml.etree.ElementTree as ET
from rdkit import Chem
from rdkit.Chem import rdDetermineBonds,rdMolDescriptors
B=Path(__file__).resolve().parent
R=B.parents[3]
S=B/'source_review'; O=B/'prepared_inputs';O.mkdir(exist_ok=True)
def dump(path,obj):path.parent.mkdir(parents=True,exist_ok=True);path.write_text(json.dumps(obj,indent=2,ensure_ascii=False)+'\n')
def coords(text):
 return [(m[0],*[float(x) for x in m[1:]]) for m in re.findall(r'^\s*([A-Z][a-z]?)\s+(-?\d+\.\d+)\s+(-?\d+\.\d+)\s+(-?\d+\.\d+)\s*$',text,re.M)]
def graph(rows,charge=0,label='',source='',radical=False):
 xyz=str(len(rows))+'\nidentity extraction only\n'+'\n'.join(row[0]+' '+ ' '.join(f'{v:.10f}' for v in row[1:]) for row in rows)+'\n'
 m=Chem.MolFromXYZBlock(xyz)
 selenium=[i for i,a in enumerate(m.GetAtoms()) if a.GetSymbol()=='Se']
 for i in selenium:m.GetAtomWithIdx(i).SetAtomicNum(16)
 rdDetermineBonds.DetermineBonds(m,charge=charge,allowChargedFragments=not radical,embedChiral=True)
 for i in selenium:m.GetAtomWithIdx(i).SetAtomicNum(34)
 for i,a in enumerate(m.GetAtoms()):a.SetAtomMapNum(i+1)
 return {'id':label,'formula':rdMolDescriptors.CalcMolFormula(m),'charge':charge,'mapped_smiles':Chem.MolToSmiles(m),'atoms':[{'atom_id':i+1,'element':a.GetSymbol(),'formal_charge':a.GetFormalCharge()} for i,a in enumerate(m.GetAtoms())],'bonds':[{'a':b.GetBeginAtomIdx()+1,'b':b.GetEndAtomIdx()+1,'order':str(b.GetBondType())} for b in m.GetBonds()],'mapping':'Stable one-based IDs in the source coordinate block; only connectivity is public. Generate independent coordinates.','source':source,'source_coordinates_public':False,'input_status':'Identity, not a predicted optimized geometry or state assignment'}
def smi_graph(s,label,source):
 m=Chem.AddHs(Chem.MolFromSmiles(s))
 for i,a in enumerate(m.GetAtoms()):a.SetAtomMapNum(i+1)
 return {'id':label,'formula':rdMolDescriptors.CalcMolFormula(m),'charge':Chem.GetFormalCharge(m),'mapped_smiles':Chem.MolToSmiles(m),'atoms':[{'atom_id':i+1,'element':a.GetSymbol(),'formal_charge':a.GetFormalCharge()} for i,a in enumerate(m.GetAtoms())],'bonds':[{'a':b.GetBeginAtomIdx()+1,'b':b.GetEndAtomIdx()+1,'order':str(b.GetBondType())} for b in m.GetBonds()],'source':source,'source_coordinates_public':False,'mapping':'Atom-map numbers are benchmark identity IDs, not inferred source XYZ indices.'}
results=[]
# CB hosts: remove all guests from the published optimised complexes and expose graph only.
pid='paper_80441aced6051d86';t=(S/(pid+'.publisher_si.txt')).read_text()
sections=re.split(r'Cartesian coordinates of optimized ',t)[1:]
for label,prefix,skip in [('CB7','CB[7]',64),('CB8','CB[8]',128)]:
 sec=next(x for x in sections if x.startswith(prefix)); rows=coords(sec)
 # Guest fragments are source-first; verify isolated host composition before graph conversion.
 host=rows[skip:]; g=graph(host,0,label,'Publisher SI Section D, Cartesian '+prefix+' complex; host-only connectivity, no binding geometry');g['multiplicity']=1
 dump(O/pid/(label+'_identity.json'),g);results.append((pid,label,len(rows),len(host),g['formula']))
# PAH identities: source name selects topology only, not the winning spin state or geometry.
pid='paper_c23cfabbd34b087f';t=(S/(pid+'.supplementary_001.full.txt')).read_text()
for label,heading in [('1M_OMe','1M-OMe:'),('1M_TIPS','1M-TIPS:'),('2M_OMe','2M-OMe (closed-shell singlet):'),('2M_TIPS','2M-TIPS (closed-shell singlet):')]:
 sec=t.split(heading,1)[1];sec=re.split(r'\n[12]M',sec)[0];rows=coords(sec)
 g=graph(rows,0,label,'SI Cartesian identity block '+heading+'; coordinates and energies withheld');g['allowed_multiplicities']=[1,3]
 dump(O/pid/(label+'_identity.json'),g);results.append((pid,label,len(rows),g['formula']))
# Cyanine identities.
pid='paper_e0791c047a731974';t=(S/(pid+'.supplementary_001.full.txt')).read_text()
for label in ['IR780','Cy1','Cy2']:
 sec=t.split(label+' S0',1)[1];sec=re.split(r'\n(?:IR780|Cy[123]) (?:S0|S1|T1|T2)',sec)[0];rows=coords(sec)
 g=graph(rows,1,label,'SI Section 5 '+label+' S0 identity only; iodide excluded');g['ground_multiplicity']=1;g['excited_multiplicities']=[1,3]
 dump(O/pid/(label+'_identity.json'),g);results.append((pid,label,len(rows),g['formula']))
# Explicit Sn ring identities, all three n-butyl substituents retained. Pair orientation generated by agent.
pid='paper_a21b91f97ce3c68f'
for label,smi in [('6','CCCC[Sn](CCCC)(CCCC)C1CCCCO1'),('7','CCCC[Sn](CCCC)(CCCC)C1OCCCO1'),('13','CCCC[Sn](CCCC)(CCCC)C1CSCSC1')]:
 g=smi_graph(smi,label,'SI Table S3: '+{'6':'6a/e, thp-ax/eq','7':'7a/e, 1,3-dioxane-ax/eq','13':'13a/e, 1,3-dithiane5-ax/eq'}[label]);g['multiplicity']=1;g['required_orientations']=['axial','equatorial']
 m=Chem.MolFromSmiles(g['mapped_smiles']);sn=next(a for a in m.GetAtoms() if a.GetSymbol()=='Sn');g['sn_atom_id']=sn.GetAtomMapNum();g['sn_carbon_neighbors']=[a.GetAtomMapNum() for a in sn.GetNeighbors()];g['anomeric_carbon_id']=next(a.GetAtomMapNum() for a in sn.GetNeighbors() if a.IsInRing());g['butyl_carbon_ids']=[i for i in g['sn_carbon_neighbors'] if i!=g['anomeric_carbon_id']]
 dump(O/pid/('pair_'+label+'_identity.json'),g);results.append((pid,label,g['formula']))
# Neutral iso-DPP graph from neutral DMSO coordinates. No acidic/basic endpoint geometry is exposed.
pid='paper_988bc12ae3768679';d=S/(pid+'.publisher_si.docx')
with zipfile.ZipFile(d) as z:
 root=ET.fromstring(z.read('word/document.xml')); ns={'w':'http://schemas.openxmlformats.org/wordprocessingml/2006/main'}
 paragraphs=[' '.join((n.text or '') for n in p.findall('.//w:t',ns)) for p in root.findall('.//w:p',ns)]
text='\n'.join(paragraphs);(S/(pid+'.publisher_si.spaced.txt')).write_text(text)
sec=re.split(r'optimized geometry of\s+2a\s+obtained',text,maxsplit=1)[1].split('Cartesian coordinates',1)[0];rows=coords(sec)
g=graph(rows,0,'2a_neutral_parent','Publisher SI neutral DMSO coordinate block; connectivity only, no assigned acid/base endpoints');g['multiplicity']=1;g['allowed_proton_change']=[-2,-1,0,1,2];g['allowed_charge']=[-2,-1,0,1,2]
g['candidate_scope']='Preserve C30N6O4 heavy-atom connectivity; permit proton addition/removal at heteroatoms and azo/hydrazone or lactam/lactim proton/bond rearrangements. Electrons unchanged except charge balances H+ exchange. Generate candidates; no site is designated the answer.'
dump(O/pid/'parent_identity.json',g);results.append((pid,'neutral_parent',len(rows),g['formula']))
dump(B/'identity_preparation_checks.json',results)
print(json.dumps(results,ensure_ascii=False))
