name: researchchem-reaction-kinetics
channels:
  - rmg
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy=1.26
  - mpi=*=mpich
  - mpich=4
  - gfortran_linux-64
  - hdf5
  - fftw
  - lapack
  - blas
  - h5py
  - bc=1.07.1
  - abinit=10.0.3
  - lammps=2024.08.29
  - ase=3.22.1
  - rmg=4.0.0
  - cantera=3.0.1
  - openbabel=3.1.1
  - xtb=6.7.1
  - crest
  - jax=0.4.35
  - jaxlib=0.4.35
  - rmsd=1.5.1
  - pydantic
  - pyyaml
  - python-dotenv
  - pip:
      # CENSO 2.1.2 is not published for Python 3.11 on public PyPI.
      - "censo @ git+https://github.com/grimme-lab/CENSO.git@1f23ec6fb1a990215f11f07379a298b542681c20"
      - CoolProp==8.0.0
      - numdifftools==0.9.42
      - gplearn==0.4.3
