"""ActionSpec declarations for molecular_dynamics."""

from __future__ import annotations

from .._spec_builders import action as _action


ACTION_SPECS = (
    _action(
            "minimize_system_energy",
            "molecular_dynamics",
            "Minimize an already parameterized system without automatically equilibrating or propagating dynamics.",
            "ParameterizedSystem",
            ("openmm", "gromacs", "lammps", "hoomd", "namd", "amber_pmemd", "charmm"),
            ("system",),
            input_description="ParameterizedSystem Artifact",
        ),
    _action(
            "calculate_force_field_energy",
            "molecular_dynamics",
            "Evaluate the total potential energy of an already parameterized system at explicitly selected stored coordinates/state without minimizing or propagating it.",
            "ForceFieldEnergyResult",
            ("openmm", "hoomd"),
            ("system",),
            input_description="backend-compatible ParameterizedSystem Artifact with explicit coordinates and force-field definition",
        ),
    _action(
            "calculate_force_field_forces",
            "molecular_dynamics",
            "Evaluate atomic force-field forces for an already parameterized system at explicitly selected stored coordinates/state.",
            "ForceResult",
            ("openmm", "hoomd"),
            ("system",),
            input_description="backend-compatible ParameterizedSystem Artifact with explicit coordinates and force-field definition",
        ),
    _action(
            "decompose_force_field_energy",
            "molecular_dynamics",
            "Decompose one OpenMM potential energy evaluation by the explicitly present Force objects without changing parameters or running dynamics.",
            "ForceFieldEnergyDecompositionResult",
            ("openmm",),
            ("system",),
            input_description="ParameterizedSystem Artifact; each existing OpenMM Force object is evaluated in its own temporary force group",
        ),
    _action(
            "propagate_dynamics",
            "molecular_dynamics",
            "Propagate exactly one agent-defined dynamics segment and return its trajectory and final state.",
            "Trajectory",
            ("openmm", "gromacs", "lammps", "hoomd", "namd", "amber_pmemd", "charmm"),
            ("system",),
            input_description="ParameterizedSystem or previous final-state Artifact",
        ),
    _action(
            "calculate_trajectory_rmsd",
            "molecular_dynamics",
            "Calculate an RMSD time series for an explicitly selected trajectory atom group and reference.",
            "TimeSeries",
            ("mdanalysis", "mdtraj"),
            ("trajectory", "topology"),
            ("reference",),
            input_description="trajectory/topology Artifacts and optional reference",
        ),
    _action(
            "calculate_radius_of_gyration",
            "molecular_dynamics",
            "Calculate the radius-of-gyration time series for an explicitly selected atom group.",
            "TimeSeries",
            ("mdanalysis", "mdtraj"),
            ("trajectory", "topology"),
            input_description="trajectory/topology Artifacts",
        ),
    _action(
            "calculate_radial_distribution",
            "molecular_dynamics",
            "Calculate one radial distribution function for two explicitly selected atom groups.",
            "DistributionResult",
            ("mdanalysis",),
            ("trajectory", "topology"),
            input_description="trajectory/topology Artifacts",
        ),
    _action(
            "calculate_mean_squared_displacement",
            "molecular_dynamics",
            "Calculate one mean-squared-displacement time series for an explicitly selected atom group.",
            "TimeSeries",
            ("mdanalysis",),
            ("trajectory", "topology"),
            input_description="trajectory/topology Artifacts",
        ),
    _action(
            "calculate_contacts",
            "molecular_dynamics",
            "Calculate inter-residue contact distances for an explicitly supplied residue-pair set and contact definition.",
            "ContactTimeSeries",
            ("mdtraj",),
            ("trajectory", "topology", "residue_pairs"),
            input_description="trajectory/topology Artifacts plus explicit zero-based residue-index pairs",
        ),
    _action(
            "calculate_solvent_accessible_surface",
            "molecular_dynamics",
            "Calculate solvent-accessible surface area per atom or residue for an existing trajectory.",
            "SurfaceAreaTimeSeries",
            ("mdtraj",),
            ("trajectory", "topology"),
            input_description="trajectory/topology Artifacts and explicit probe/sphere discretization settings",
        ),
    _action(
            "calculate_dihedral_distribution",
            "molecular_dynamics",
            "Calculate dihedral-angle time series for explicitly supplied atom-index quartets.",
            "DihedralTimeSeries",
            ("mdtraj", "mdanalysis"),
            ("trajectory", "topology", "atom_quartets"),
            input_description="trajectory/topology Artifacts plus explicit zero-based atom-index quartets",
        ),
    _action(
            "calculate_hydrogen_bonds",
            "molecular_dynamics",
            "Identify hydrogen-bond events in an existing trajectory using explicit donor, hydrogen, acceptor, distance, and angle definitions.",
            "HydrogenBondResult",
            ("mdanalysis",),
            ("trajectory", "topology"),
            ("between_selections",),
            input_description="trajectory/topology Artifacts plus explicit MDAnalysis selections and geometric cutoffs",
        ),
    _action(
            "calculate_principal_components",
            "molecular_dynamics",
            "Calculate coordinate principal components and frame projections for an explicitly selected trajectory atom group.",
            "PrincipalComponentResult",
            ("mdanalysis",),
            ("trajectory", "topology"),
            input_description="trajectory/topology Artifacts plus explicit atom selection, alignment policy, frame slice, and component count",
        ),
    _action(
            "calculate_dynamic_cross_correlation",
            "molecular_dynamics",
            "Calculate an atom-wise dynamic cross-correlation matrix from explicitly selected and optionally aligned trajectory coordinates.",
            "DynamicCrossCorrelationResult",
            ("mdanalysis",),
            ("trajectory", "topology"),
            input_description="trajectory/topology Artifacts plus explicit analysis/alignment selections and frame slice",
        ),
    _action(
            "assign_secondary_structure",
            "molecular_dynamics",
            "Assign per-residue secondary-structure labels for every frame of an existing protein trajectory.",
            "SecondaryStructureTimeSeries",
            ("mdtraj",),
            ("trajectory", "topology"),
            input_description="existing trajectory/topology Artifacts and explicit DSSP label granularity",
        ),
    _action(
            "cluster_trajectory",
            "molecular_dynamics",
            "Cluster explicitly selected trajectory frames by RMSD using a deterministic cutoff-based leader assignment.",
            "TrajectoryClusterResult",
            ("mdtraj",),
            ("trajectory", "topology"),
            input_description="existing trajectory/topology Artifacts plus explicit atom indices, frame stride, RMSD cutoff, and cluster bound",
        ),
    _action(
            "evaluate_collective_variables",
            "molecular_dynamics",
            "Evaluate explicitly defined collective variables on an existing trajectory.",
            "TimeSeries",
            ("plumed",),
            ("trajectory", "topology", "collective_variables"),
            input_description="trajectory/topology plus typed collective-variable definitions",
        ),
    _action(
            "estimate_free_energy_difference",
            "molecular_dynamics",
            "Estimate dimensionless pairwise free-energy differences from an explicitly supplied reduced-potential matrix and sample counts.",
            "FreeEnergyDifferenceResult",
            ("pymbar",),
            ("reduced_potentials", "samples_per_state"),
            input_description="u_kn reduced-potential matrix with shape KxN and aligned N_k sample counts",
        ),
    _action(
            "estimate_thermodynamic_expectations",
            "molecular_dynamics",
            "Estimate state-resolved observable expectations from explicitly supplied samples and a reduced-potential matrix.",
            "ThermodynamicExpectationResult",
            ("pymbar",),
            ("reduced_potentials", "samples_per_state", "observables"),
            input_description="u_kn matrix, aligned N_k counts, and one N-sample observable vector",
        ),
    _action(
            "calculate_potential_of_mean_force",
            "molecular_dynamics",
            "Estimate a one-dimensional histogram free-energy profile from supplied uncorrelated samples; this does not integrate a mean-force trajectory or choose bins for the agent.",
            "FreeEnergyProfileResult",
            ("pymbar",),
            (
                "reduced_potentials", "samples_per_state", "target_reduced_potential",
                "collective_variable",
            ),
            input_description="u_kn/N_k, one target-state reduced potential per sample, one scalar coordinate per sample, and explicit bin edges",
        ),
    _action(
            "analyze_free_energy_convergence",
            "molecular_dynamics",
            "Re-estimate one explicitly selected pairwise free-energy difference over supplied sample fractions without generating or decorrelating samples.",
            "FreeEnergyConvergenceResult",
            ("pymbar",),
            ("reduced_potentials", "samples_per_state"),
            input_description="u_kn matrix with samples grouped by source state, N_k counts, explicit fractions, and one state pair",
        ),
    _action(
            "parse_alchemical_energy_data",
            "molecular_dynamics",
            "Parse one or more explicitly identified engine output files into a normalized alchemical reduced-potential or derivative table.",
            "AlchemicalEnergyData",
            ("alchemlyb",),
            ("files",),
            input_description="workspace output-file Artifacts plus explicit engine, observable, and simulation temperature",
        ),
)
