"""ActionSpec declarations for structure_and_system."""

from __future__ import annotations

from .._spec_builders import action as _action


ACTION_SPECS = (
    _action(
            "standardize_structure",
            "structure_and_system",
            "Standardize one molecular representation without generating 3D coordinates or optimizing geometry.",
            "AtomicStructure",
            ("rdkit",),
            ("structure",),
            input_description="structure: SMILES or a molecule/structure object",
        ),
    _action(
            "generate_3d_structure",
            "structure_and_system",
            "Generate one explicit three-dimensional structure from a two-dimensional molecular representation.",
            "AtomicStructure",
            ("rdkit", "openbabel"),
            ("molecule",),
            input_description="molecule: standardized SMILES or molecule object",
        ),
    _action(
            "generate_conformer_ensemble",
            "structure_and_system",
            "Generate a conformer ensemble; it does not perform the later quantum refinement or final ranking workflow.",
            "ConformerEnsemble",
            ("rdkit_etkdg", "crest"),
            ("molecule",),
            ("initial_structure",),
            input_description="molecule plus optional initial_structure Artifact for CREST",
            batch_safe=True,
        ),
    _action(
            "cluster_conformers",
            "structure_and_system",
            "Cluster an already supplied conformer ensemble by an explicit heavy/all-atom RMSD cutoff without generating or ranking conformers.",
            "ConformerClusterResult",
            ("rdkit",),
            ("ensemble",),
            input_description="ConformerEnsemble Artifact or structured ensemble plus an explicit RMSD clustering policy",
        ),
    _action(
            "align_molecular_structures",
            "structure_and_system",
            "Rigidly align one supplied 3D probe structure to a reference using an explicit atom-to-atom map.",
            "StructureAlignmentResult",
            ("rdkit",),
            ("reference", "probe", "atom_map"),
            input_description="two coordinate-bearing molecular structures and explicit [probe_index, reference_index] atom pairs",
        ),
    _action(
            "rank_conformers_from_results",
            "structure_and_system",
            "Rank and weight conformers only from aligned energies or free energies already supplied by the agent.",
            "ConformerEnsemble",
            ("internal_statistics",),
            ("ensemble", "scores"),
            input_description="ensemble and one aligned score record per conformer",
            selection_policy="internal_deterministic",
        ),
    _action(
            "enumerate_coordination_isomers",
            "structure_and_system",
            "Enumerate symmetry-distinct ligand-to-site assignments for an explicitly selected coordination geometry without inventing coordinates or ranking their energies.",
            "CoordinationIsomerAssignments",
            ("internal_reaction_analysis",),
            ("structure", "coordination_center_index", "ligand_anchor_indices"),
            ("ligand_labels",),
            input_description="one fixed structure, zero-based center/anchor indices, and optional labels identifying chemically equivalent ligands",
            selection_policy="internal_deterministic",
        ),
    _action(
            "repair_biomolecular_structure",
            "structure_and_system",
            "Repair missing biomolecular residues or atoms without choosing protonation, force field, solvent, or dynamics settings.",
            "AtomicStructure",
            ("pdbfixer",),
            ("structure",),
            input_description="biomolecular structure or workspace PDB Artifact",
        ),
    _action(
            "select_structure_subset",
            "structure_and_system",
            "Select explicit chains and/or models from one PDB structure, with an explicit choice about retaining heteroatom records.",
            "AtomicStructure",
            ("pdb_tools",),
            ("structure",),
            input_description="workspace PDB Artifact plus explicit chain/model filters",
            selection_policy="internal_deterministic",
        ),
    _action(
            "renumber_biomolecular_structure",
            "structure_and_system",
            "Renumber PDB atom serials and residue identifiers from explicit starting values without changing coordinates or chemistry.",
            "AtomicStructure",
            ("pdb_tools",),
            ("structure",),
            input_description="workspace PDB Artifact and explicit starting serial/residue values",
            selection_policy="internal_deterministic",
        ),
    _action(
            "normalize_pdb_records",
            "structure_and_system",
            "Sort and format one PDB record stream under explicit ordering, chain-break, and hybrid-36 choices.",
            "AtomicStructure",
            ("pdb_tools",),
            ("structure",),
            input_description="workspace PDB Artifact and explicit PDB formatting policy",
            selection_policy="internal_deterministic",
        ),
    _action(
            "assign_protonation_states",
            "structure_and_system",
            "Assign explicit protonation states using the agent-selected backend and pH/rule settings.",
            "AtomicStructure",
            ("rdkit", "pdbfixer"),
            ("structure",),
            input_description="standardized or repaired structure",
        ),
    _action(
            "assign_partial_charges",
            "structure_and_system",
            "Assign named force-field or docking partial charges without parameterizing or solvating the system.",
            "ChargedStructure",
            ("rdkit_gasteiger", "openff_am1bcc"),
            ("structure",),
            input_description="structure with the desired protonation state already fixed",
        ),
    _action(
            "assign_force_field_parameters",
            "structure_and_system",
            "Assign an explicitly selected force field to an already prepared molecular system.",
            "ParameterizedSystem",
            ("openff", "openmm_builder"),
            ("structure",),
            ("charges",),
            input_description="prepared structure plus optional ChargedStructure Artifact",
        ),
    _action(
            "solvate_molecular_system",
            "structure_and_system",
            "Build the explicitly requested solvent/ion environment without minimizing or propagating dynamics.",
            "ParameterizedSystem",
            ("openmm_builder", "packmol"),
            ("system",),
            input_description="ParameterizedSystem plus explicit box, solvent, and ion settings",
        ),
    _action(
            "analyze_crystal_symmetry",
            "structure_and_system",
            "Determine the crystallographic space group and symmetry-equivalent sites for one supplied periodic structure.",
            "CrystalSymmetryResult",
            ("spglib", "pymatgen"),
            ("structure",),
            input_description="periodic AtomicStructure plus explicit symmetry tolerances",
        ),
    _action(
            "standardize_crystal_structure",
            "structure_and_system",
            "Standardize one periodic structure in an explicitly selected primitive or conventional crystallographic setting.",
            "AtomicStructure",
            ("spglib", "pymatgen"),
            ("structure",),
            input_description="periodic AtomicStructure and explicit primitive/conventional convention",
        ),
    _action(
            "build_supercell",
            "structure_and_system",
            "Apply one explicit integer supercell transformation to a periodic structure.",
            "AtomicStructure",
            ("pymatgen",),
            ("structure",),
            input_description="periodic AtomicStructure and an integer 3-vector or 3x3 scaling matrix",
        ),
    _action(
            "enumerate_surface_slabs",
            "structure_and_system",
            "Enumerate a bounded set of symmetry-distinct slabs for one explicit Miller index and slab/vacuum geometry.",
            "StructureCollection",
            ("pymatgen",),
            ("structure",),
            input_description="periodic bulk structure and explicit Miller index, thicknesses, and enumeration bound",
        ),
)
