#!/usr/bin/env python3
"""Register project-local MCP prefixes as named Conda environments.

Conda does not store an independent name inside an environment.  A name is the
directory entry beneath one of Conda's ``envs_dirs``.  ResearchChemBench keeps
large environments beside the project, so this script creates stable, named
symlinks without copying or relocating any prefix.

It also installs small runtime hooks.  The hooks put the active prefix's native
libraries first, and selected PyTorch/MACE environments preload their own C++
runtime before pip wheels can load the older system ``libstdc++``.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
from pathlib import Path
from typing import Any

import yaml
from dotenv import dotenv_values


TOOLBOX_ROOT = Path(__file__).resolve().parents[1]
ROOT = TOOLBOX_ROOT.parent
CONFIG_PATH = TOOLBOX_ROOT / "config" / "mcp_profiles.yaml"
LOCAL_CONFIG_PATH = ROOT / "config.local.env"
ALIAS_DIR = ROOT / ".conda_envs"
MODEL_CACHE_ENV = "RESEARCHCHEMBENCH_MODEL_CACHE"


def load_environments() -> list[dict[str, Any]]:
    config = yaml.safe_load(CONFIG_PATH.read_text(encoding="utf-8")) or {}
    local_values = dotenv_values(LOCAL_CONFIG_PATH) if LOCAL_CONFIG_PATH.exists() else {}
    configured_cache = (
        os.environ.get(MODEL_CACHE_ENV, "")
        or str(local_values.get(MODEL_CACHE_ENV) or "")
    ).strip()
    model_cache = Path(
        configured_cache or str(config.get("model_cache_root") or ".model_cache")
    ).expanduser()
    if not model_cache.is_absolute():
        model_cache = ROOT / model_cache
    model_cache = model_cache.resolve()
    entries: list[dict[str, Any]] = []
    for group in ("profiles", "support_environments"):
        for key, specification in (config.get(group) or {}).items():
            conda_name = str(specification.get("conda_name") or "").strip()
            if not conda_name:
                raise ValueError(f"{group}.{key} must define conda_name")
            environment = Path(str(specification["environment"])).expanduser()
            if not environment.is_absolute():
                environment = ROOT / environment
            entries.append(
                {
                    "key": key,
                    "group": group,
                    "conda_name": conda_name,
                    "environment": environment.resolve(),
                    "preload_libraries": list(
                        specification.get("runtime_preload_libraries") or []
                    ),
                    "model_cache": (
                        model_cache
                        if specification.get("use_project_model_cache", False)
                        else None
                    ),
                }
            )
    names = [entry["conda_name"] for entry in entries]
    if len(names) != len(set(names)):
        raise ValueError("conda_name values must be unique")
    return entries


def write_runtime_hooks(entry: dict[str, Any], *, dry_run: bool) -> None:
    environment: Path = entry["environment"]
    if not (environment / "conda-meta").is_dir():
        return

    activate = environment / "etc" / "conda" / "activate.d" / "researchchem_runtime.sh"
    deactivate = environment / "etc" / "conda" / "deactivate.d" / "researchchem_runtime.sh"
    activate_text = """# Generated by ResearchChemBench.\n\
export _RESEARCHCHEM_OLD_LD_LIBRARY_PATH=\"${LD_LIBRARY_PATH-}\"\n\
export LD_LIBRARY_PATH=\"$CONDA_PREFIX/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}\"\n"""
    deactivate_text = """# Generated by ResearchChemBench.\n\
if [[ -n \"${_RESEARCHCHEM_OLD_LD_LIBRARY_PATH+x}\" ]]; then\n\
  export LD_LIBRARY_PATH=\"$_RESEARCHCHEM_OLD_LD_LIBRARY_PATH\"\n\
  unset _RESEARCHCHEM_OLD_LD_LIBRARY_PATH\n\
fi\n"""

    model_cache: Path | None = entry["model_cache"]
    if model_cache is not None:
        activate_text += f'''export _RESEARCHCHEM_HAD_MODEL_CACHE="${{{MODEL_CACHE_ENV}+x}}"
export _RESEARCHCHEM_OLD_MODEL_CACHE="${{{MODEL_CACHE_ENV}-}}"
export _RESEARCHCHEM_HAD_XDG_CACHE_HOME="${{XDG_CACHE_HOME+x}}"
export _RESEARCHCHEM_OLD_XDG_CACHE_HOME="${{XDG_CACHE_HOME-}}"
if [[ -z "${{{MODEL_CACHE_ENV}:-}}" ]]; then
  export {MODEL_CACHE_ENV}={str(model_cache)!r}
fi
export XDG_CACHE_HOME="${{{MODEL_CACHE_ENV}}}"
'''
        deactivate_text += f'''if [[ "${{_RESEARCHCHEM_HAD_XDG_CACHE_HOME-}}" == "x" ]]; then
  export XDG_CACHE_HOME="$_RESEARCHCHEM_OLD_XDG_CACHE_HOME"
else
  unset XDG_CACHE_HOME
fi
unset _RESEARCHCHEM_HAD_XDG_CACHE_HOME _RESEARCHCHEM_OLD_XDG_CACHE_HOME
if [[ "${{_RESEARCHCHEM_HAD_MODEL_CACHE-}}" == "x" ]]; then
  export {MODEL_CACHE_ENV}="$_RESEARCHCHEM_OLD_MODEL_CACHE"
else
  unset {MODEL_CACHE_ENV}
fi
unset _RESEARCHCHEM_HAD_MODEL_CACHE _RESEARCHCHEM_OLD_MODEL_CACHE
'''

    if not dry_run:
        activate.parent.mkdir(parents=True, exist_ok=True)
        deactivate.parent.mkdir(parents=True, exist_ok=True)
        if model_cache is not None:
            model_cache.mkdir(parents=True, exist_ok=True)
        activate.write_text(activate_text, encoding="utf-8")
        deactivate.write_text(deactivate_text, encoding="utf-8")

    libraries = entry["preload_libraries"]
    if not libraries and model_cache is None:
        return
    site_packages = sorted(environment.glob("lib/python*/site-packages"))
    if not site_packages:
        raise FileNotFoundError(f"No site-packages directory in {environment}")
    cache_setup = ""
    if model_cache is not None:
        cache_setup = f'''_cache_root = Path(
    os.environ.get({MODEL_CACHE_ENV!r}, "") or {str(model_cache)!r}
).expanduser().resolve()
_cache_root.mkdir(parents=True, exist_ok=True)
os.environ[{MODEL_CACHE_ENV!r}] = str(_cache_root)
os.environ["XDG_CACHE_HOME"] = str(_cache_root)

'''
    module_text = f'''"""Apply ResearchChemBench's cache and native-runtime policy."""\n\n\
from __future__ import annotations\n\n\
import ctypes\n\
import os\n\
import sys\n\
from pathlib import Path\n\n\n\
{cache_setup}\
for _library in {tuple(str(item) for item in libraries)!r}:\n\
    _candidate = Path(sys.prefix) / "lib" / _library\n\
    if _candidate.is_file():\n\
        ctypes.CDLL(str(_candidate), mode=ctypes.RTLD_GLOBAL)\n'''
    for site_directory in site_packages:
        if dry_run:
            continue
        (site_directory / "researchchem_runtime.py").write_text(
            module_text, encoding="utf-8"
        )
        (site_directory / "researchchem_runtime.pth").write_text(
            "import researchchem_runtime\n", encoding="utf-8"
        )


def create_alias(entry: dict[str, Any], *, dry_run: bool) -> Path:
    environment: Path = entry["environment"]
    alias = ALIAS_DIR / entry["conda_name"]
    if not (environment / "conda-meta").is_dir():
        print(f"skip missing environment: {entry['conda_name']} -> {environment}")
        return alias
    if alias.is_symlink():
        if alias.resolve() == environment:
            return alias
        if not dry_run:
            alias.unlink()
    elif alias.exists():
        raise FileExistsError(f"Named environment path already exists: {alias}")
    if not dry_run:
        ALIAS_DIR.mkdir(parents=True, exist_ok=True)
        relative_target = os.path.relpath(environment, ALIAS_DIR)
        alias.symlink_to(relative_target, target_is_directory=True)
    return alias


def configure_conda(conda: str, *, dry_run: bool) -> None:
    completed = subprocess.run(
        [conda, "config", "--show", "envs_dirs", "--json"],
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    configured: list[str] = []
    if completed.returncode == 0:
        try:
            configured = list(json.loads(completed.stdout).get("envs_dirs") or [])
        except json.JSONDecodeError:
            configured = []
    if str(ALIAS_DIR) not in configured:
        command = [conda, "config", "--append", "envs_dirs", str(ALIAS_DIR)]
        print("+ " + " ".join(command))
        if not dry_run:
            subprocess.run(command, check=True)


def prune_prefix_registry(entries: list[dict[str, Any]], *, dry_run: bool) -> None:
    registry = Path.home() / ".conda" / "environments.txt"
    if not registry.is_file():
        return
    original = registry.read_text(encoding="utf-8").splitlines()
    raw_prefixes = {str(entry["environment"]) for entry in entries}
    retained = [line for line in original if line.strip() not in raw_prefixes]
    if retained != original and not dry_run:
        registry.write_text("\n".join(retained) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--conda", default="")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument(
        "--no-conda-config",
        action="store_true",
        help="Create aliases/hooks without adding the alias directory to Conda envs_dirs.",
    )
    parser.add_argument(
        "--keep-prefix-registry",
        action="store_true",
        help="Keep raw project prefixes in ~/.conda/environments.txt.",
    )
    args = parser.parse_args()

    entries = load_environments()
    conda = args.conda or shutil.which("conda")
    if not conda and not args.no_conda_config:
        raise SystemExit("conda was not found; pass --conda or --no-conda-config")

    for entry in entries:
        alias = create_alias(entry, dry_run=args.dry_run)
        write_runtime_hooks(entry, dry_run=args.dry_run)
        if (entry["environment"] / "conda-meta").is_dir():
            print(f"{entry['conda_name']}: {alias} -> {entry['environment']}")

    if not args.no_conda_config:
        configure_conda(str(conda), dry_run=args.dry_run)
    if not args.keep_prefix_registry:
        prune_prefix_registry(entries, dry_run=args.dry_run)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
