"""Build the batch-3 development task contracts; never modifies source/final packages."""
from pathlib import Path
from copy import deepcopy
import sys,json,hashlib,re
B=Path(__file__).parent;ROOT=B.resolve().parents[3];sys.path.insert(0,str(ROOT));sys.path.insert(0,str(B))
from science_specs import S
from evaluation.contracts.task_package import package_payload_entries,package_content_hash,PackageManifest
D=ROOT/'tasks/upgrade_tasks';A=json.load(open(B/'assignment.json'));ASS={x['paper_id']:x for x in A['records']}
def dump(p,x):p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(x,indent=2,ensure_ascii=False)+'\n')
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
STR={'type':'string','minLength':1};NUM={'type':'number'};PATH={'type':'string','pattern':r'^(?:\./)?(?:outputs|structures|analysis|logs)/(?!(?:.*\/)?\.\.(?:/|$))[^\\\x00]+$'}
def obj(props,required=None):return {'type':'object','properties':props,'required':list(props) if required is None else required,'additionalProperties':False}
def arr(item,minItems=1):return {'type':'array','items':item,'minItems':minItems}
def en(*values):return {'enum':list(values)}
def ref(pid):
 return {'9455a82229de2427':'separated_SiN_plus_isoprene_E0_0K','36722b90a0c12825':'balanced_binding_G_298K_1M','86a0b654270a8ce7':'isomer2_minus_isomer1_G_339K_THF','c28b0a1c549f4575':'balanced_neutral_salt_PC_exchange','3a22e838133b906d':'balanced_full_species_association_and_deethylation','b1467cd61ca8022d':'equal_stoichiometry_LiFSI_solvent_and_explicit_fragments'}.get(pid[6:],'matched_object_state_geometry_protocol')
def row_schema(panel,rowid):
 metrics={m:dict(NUM,description=metric_description(m)) for m in panel['metrics']}
 metrics.update(deepcopy(panel.get('metric_overrides',{}).get(rowid,{})))
 s=obj({'outcome':en('computed','evidenced_collapse'),'calculation_ids':arr(STR),'atom_map_file':PATH,'raw_files':arr(PATH),'data_table_file':PATH,'metrics':obj(metrics),'collapse_evidence':arr(PATH,2),'mapped_retained_endpoint':STR,'interpretation':STR},['outcome','calculation_ids','atom_map_file','raw_files','data_table_file','interpretation'])
 s['allOf']=[{'if':{'properties':{'outcome':{'const':'computed'}}},'then':{'required':['metrics']}},{'if':{'properties':{'outcome':{'const':'evidenced_collapse'}}},'then':{'required':['collapse_evidence','mapped_retained_endpoint']}}]
 s['description']=rowid+': '+panel['criterion']+' Collapses require actual mapped before/after structures and endpoint evidence, not a failed job.'
 if panel['name'] not in ['stoichiometric_series','conformer_environment','relaxed_models','oxidation_pairs','isomer_ensembles','state_geometry','cluster_orientations','equal_composition_clusters','coordination_layers']:
  s['properties']['outcome']={'const':'computed'}
 return s
def metric_description(name):
 unit=next((u for s,u in [('_Eh','hartree'),('_kJ_mol','kJ/mol'),('_eV_per_A','eV/angstrom'),('_eV','eV'),('_A','angstrom'),('_degree','degree'),('_cm1','cm^-1'),('_s1','s^-1'),('_D','debye'),('_eA2','e angstrom^2'),('_e','elementary charge')] if name.endswith(s)),'dimensionless')
 return name+'; unit '+unit+'. Derive from cited actual raw calculations, with state/geometry/protocol stated. This field is not a supplied reference target.'
def schema(pid,s,objects):
 identity_variants=[]
 for o in objects:
  identity_variants.append(obj({'object_id':{'const':o['id']},'charge':{'const':o['charge']},'multiplicity':{'const':o['multiplicity']},'graph_file':PATH,'geometry_file':PATH,'atom_map_file':PATH,'validation_file':PATH}))
 if pid.endswith('9455a82229de2427'):
  for category,q,m,comp in [('doublet_surface',0,2,'C5H8NSi'),('singlet_product',0,1,'C5H7NSi')]:
   identity_variants.append(obj({'object_id':{'type':'string','pattern':'^candidate_[A-Za-z0-9_]+$'},'candidate_category':{'const':category},'formula':{'const':comp},'charge':{'const':q},'multiplicity':{'const':m},'graph_file':PATH,'geometry_file':PATH,'atom_map_file':PATH,'validation_file':PATH}))
 # Object entries are a finite validated catalog; composite counts live in public objects.json.
 job=obj({'id':STR,'object_id':STR,'kind':en('successful','failed'),'role':en('optimization_frequency','single_point','TD','excited_optimization','path','density_analysis'),'input_file':PATH,'output_file':PATH,'geometry_file':PATH,'electronic_Eh':NUM,'ZPE_Eh':NUM,'thermal_Eh':NUM,'state_label':STR,'convergence_file':PATH,'failure_diagnostics':STR},['id','object_id','kind','role','input_file','output_file','state_label'])
 job['properties']['object_id']={'anyOf':[{'enum':[o['id'] for o in objects]}]+([{'type':'string','pattern':'^candidate_[A-Za-z0-9_]+$'}] if pid.endswith('9455a82229de2427') else [])}
 job['allOf']=[{'if':{'properties':{'kind':{'const':'successful'}}},'then':{'required':['convergence_file']}},{'if':{'properties':{'kind':{'const':'successful'},'role':{'not':{'const':'density_analysis'}}}},'then':{'required':['geometry_file','electronic_Eh']}},{'if':{'properties':{'kind':{'const':'failed'}}},'then':{'required':['failure_diagnostics']}}]
 protocol=obj({'software_version':STR,'method':STR,'basis_ecp':STR,'environment':STR,'temperature_K':dict(NUM,minimum=0),'standard_state':STR,'energy_reference':{'const':ref(pid)},'thermal_and_low_frequency':STR,'state_tracking':STR,'numerical_convergence':STR})
 result_panels={p['name']:obj({r:row_schema(p,r) for r in p['rows']}) for p in s['panels']}
 hyp=obj({'id':STR,'claim':STR,'rival':STR,'discriminating_comparison':STR,'calculation_ids':arr(STR),'predicted_discriminator':STR,'observed_contrast':NUM,'unit':STR,'outcome':en('supported','refuted','unresolved'),'evidence_files':arr(PATH)})
 sensitivity=obj({'factor':STR,'primary_value':NUM,'control_value':NUM,'unit':STR,'difference':NUM,'uncertainty':dict(NUM,minimum=0),'uncertainty_basis':STR,'calculation_ids':arr(STR,2),'raw_files':arr(PATH,2)})
 failure=obj({'observed_failure':STR,'attempted_scope':STR,'missing_endpoints':arr(STR),'next_required_evidence':STR,'raw_files':arr(PATH)})
 scientific=obj({'outcome':en('supported','refuted','indistinguishable'),'statement':STR,'supporting_rows':arr(STR),'limitations':arr(STR),'core_matrix_complete':{'const':True}})
 props={'paper_id':{'const':pid},'status':en('complete','partial','bounded_failure'),'protocol':protocol,'object_records':arr({'oneOf':identity_variants}),'calculation_records':arr(job),'results':obj(result_panels),'hypothesis_tests':arr(hyp,2),'sensitivity':sensitivity,'conclusion':scientific,'raw_files':arr(PATH),'resources':obj({'engine_starts':{'type':'integer','minimum':0},'failed_starts':{'type':'integer','minimum':0},'restart_starts':{'type':'integer','minimum':0},'allocated_cores':{'type':'integer','minimum':1},'summed_job_hours':dict(NUM,minimum=0),'calendar_hours':dict(NUM,minimum=0),'core_hours':dict(NUM,minimum=0),'measurement_basis':STR}),'failure_report':failure}
 root=obj(props,['paper_id','status','protocol','object_records','calculation_records','raw_files','resources']);root['$schema']='https://json-schema.org/draft/2020-12/schema'
 root['properties']['object_records']['minItems']=0
 root['properties']['calculation_records']['minItems']=0
 root['properties']['resources']['properties']['allocated_cores']['minimum']=0
 root['allOf']=[{'if':{'properties':{'status':{'const':'complete'}}},'then':{'required':['results','hypothesis_tests','sensitivity','conclusion'],'properties':{'calculation_records':{'contains':{'properties':{'kind':{'const':'successful'}},'required':['kind']},'minContains':1}}}},{'if':{'properties':{'status':{'enum':['partial','bounded_failure']}}},'then':{'required':['failure_report']}}]
 complete=root['allOf'][0]['then']['properties']
 complete['calculation_records']['minItems']=1
 complete['calculation_records']['contains']['properties']['role']={'not':{'const':'density_analysis'}}
 complete['calculation_records']['contains']['required'].append('role')
 complete['resources']={'properties':{'allocated_cores':{'minimum':1}}}
 required_objects=[o['id'] for o in objects if o['id']!='TBA']
 root['allOf'][0]['then']['properties']['object_records']={'allOf':[{'contains':{'properties':{'object_id':{'const':oid}},'required':['object_id']}} for oid in required_objects]}
 root['allOf'][0]['then']['properties']['object_records']['minItems']=1
 if pid.endswith('9455a82229de2427'):
  for category in ['doublet_surface','singlet_product']:root['allOf'][0]['then']['properties']['object_records']['allOf'].append({'contains':{'properties':{'candidate_category':{'const':category}},'required':['candidate_category']}})
 if s['block']:root['properties']['status']=en('partial','bounded_failure')
 return {'paper_id':pid,'schema_version':'batch3-upgrade.v1','required_files':['report/results.json','report/report.md'],'primary_result_file':'report/results.json','report_file':'report/report.md','result_schema':root,'scientific_boundary':'Contract acceptance is not scientific acceptance. Linked files require evaluator verification, including correct graph, state, raw output, coverage and recomputable quantities. Missing controls cannot be labeled indistinguishable.','development_status':'blocked' if s['block'] else 'implemented_pending_expanded_reference'}

def evidence_sources(pid,s):
 out=[];folder=ROOT/'papers'/pid/'documents'
 for p in sorted(folder.glob('*.pdf')):
  if pid.endswith('b1467cd61ca8022d') and p.name!='main.pdf':continue
  if pid.endswith('2877efc02814175d') and p.name=='main.pdf':continue
  out.append({'path':str(p.relative_to(ROOT)),'sha256':sha(p),'locator':s['source'],'role':'source_original_scope_not_expanded_reference'})
 for suffix in ['_official_si.pdf','_official_si.docx']:
  p=B/'evidence'/(pid+suffix)
  if p.exists():out.append({'path':str(p.relative_to(ROOT)),'sha256':sha(p),'locator':s['source'],'role':'formal_publisher_SI'})
 if pid.endswith('2877efc02814175d'):
  p=ROOT/'docs/verification/group_2'/pid/'source_data/user_supplied_20260925/1-s2.0-S0022286025023567-main.pdf';out.append({'path':str(p.relative_to(ROOT)),'sha256':sha(p),'locator':'Recovered main PDF pp2,7-8 computational methods, structures and electronic analysis','role':'recovered_readable_primary_source'})
 return out

def implement(pid):
 s=S[pid];asgn=ASS[pid];status='blocked' if s['block'] else 'implemented_pending_expanded_reference'
 pub=D/'autonomous_research'/pid/'agent_input';objects=json.load(open(pub/'data/inputs/objects.json'))['objects'];contract=schema(pid,s,objects);sources=evidence_sources(pid,s)
 guidance='\n\n# Author-provided scientific guidance\n\n'+s['author']
 core='\n\n# Public inputs and scientific boundaries\n\n'+s['boundary']+'\n\nRead `data/inputs/objects.json`, `controls.json` and `data_provenance.json` together. Atom and component maps define identity; geometric preparation is independent. A supplied experimental CIF or observation is an authorized input, never a blind prediction target. Only the materialized public files may be used; no paper/SI reference outputs or private evaluator access.\n\n'
 if s['block']:core+='**Development input block.** '+s['block']+' This development package accepts diagnostic/partial submissions only until a new reviewed version resolves the input block.\n\n'
 core+='# Required scientific validation/investigation\n\n'
 for i,p in enumerate(s['panels'],1):core+=f'{i}. **{p["name"]}.** Cover '+', '.join('`'+r+'`' for r in p['rows'])+'. '+p['criterion']+' Required numeric fields are '+', '.join('`'+m+'`' for m in p['metrics'])+'.\n\n'
 core+='Formulate at least two distinguishable explanations before the decisive comparison. Use actual paired calculations capable of refuting the favored explanation, and quantify one method, conformer, state or numerical sensitivity. Equivalent controls are acceptable only if they retain every named scientific contrast and explicit atom/stoichiometry mapping; explain the substitution in the corresponding matrix row. Preserve all failed/restarted attempts. Report real basin collapse with mapped trajectories/structures; do not create fictitious independent minima. Nonstationary constrained points cannot inherit thermal corrections from another geometry.\n\nScientific completion requires all core contrasts, raw evidence and the resulting inference. Support, refutation and evidence-backed indistinguishability are equally eligible. Missing endpoints, an unverified graph or nonconvergence are incomplete work, not indistinguishability. No published winner or arbitrary numerical tolerance is imposed on uncalibrated extensions.\n\n**Optional scope.** '+s['optional']+' Optional omissions never cause core failure.\n\n# Deliverables\n\nSubmit `report/results.json` conforming to `submission_schema.json` and a readable `report/report.md`. Include machine-readable per-point/per-state/conformer tables, actual inputs and raw engine outputs, structures, mappings and density/path/frequency evidence under `outputs/`, `structures/`, `analysis/` or `logs/`. Numeric summaries must be independently recoverable from those artifacts. Report uncertainty and resource use with actual engine starts, failures/restarts, summed job hours, calendar time and core hours. A bounded failure is a valid diagnostic submission, not scientific completion.\n'
 title='# Scientific objective\n\n'+s['objective']
 evals={};criteria=[('identity',10,'Correct complete objects, conserved stoichiometry, declared states and energy reference. Validate actual atom maps and raw calculation identity before dependent scores. '+s['boundary'],['$.object_records','$.protocol','$.calculation_records'])]
 for p,w in zip(s['panels'],[20,25,20]):criteria.append((p['name'],w,p['criterion']+' Core rows: '+', '.join(p['rows'])+'. Recompute '+', '.join(p['metrics'])+' from the submitted linked raw outputs and numeric tables. No narrative-only control or reused old scalar receives endpoint credit.',['$.results.'+p['name'],'$.calculation_records']))
 criteria += [('discrimination',15,'Check actual rival tests and quantified sensitivity, not the presence of prose fields. Recalculate reported signed differences and uncertainty from at least two real computations. Do not reward repetition of author claims.',['$.hypothesis_tests','$.sensitivity']),('conclusion',10,'Accept support, refutation or computed indistinguishability only after all core comparisons and validity checks. Missing measurements/controls are unfinished, not a scientific negative. '+s['optional'],['$.conclusion','$.results'])]
 kp=[];rules=[];rubric=[]
 for key,w,statement,fields in criteria:
  rid='rule_'+key;reference='final_inference' if key=='conclusion' else 'kp_'+key
  if key!='conclusion':kp.append({'key_point_id':reference,'statement':statement,'expected':statement,'evidence_ids':['source_main_si','benchmark_design']})
  rules.append({'rule_id':rid,'reference_id':reference,'type':'condition' if key=='identity' else 'semantic','expected':statement,'binding':{'artifact_paths':['report/results.json','report/report.md'],'fields':fields,'comparison':statement},'evidence_policy':'Open referenced input/output/geometry and numeric-table artifacts. Check file hashes, successful termination, real state/minimum/path evidence, recomputed units and arithmetic. JSON flags and synthetic fixtures are never scientific evidence.'})
  rubric.append({'id':key,'max_score':w,'description':statement,'rule_ids':[rid]})
 evals['reference_key_points.json']={'paper_id':pid,'items':kp}
 final='Bounded inference about '+s['objective'][0].lower()+s['objective'][1:]+'. All required contrasts and one actual robustness check govern the conclusion; the source claim is not the required answer.'
 evals['reference_conclusions.json']={'paper_id':pid,'items':[{'conclusion_id':'final_inference','claim_role':'final','statement':final,'expected':final,'supporting_key_point_ids':[p['key_point_id'] for p in kp],'evidence_ids':['source_main_si','benchmark_design']}]}
 evals['scoring_rules.json']={'paper_id':pid,'scoring_policy':'dual_axis_100.scientific_results.v1','rules':rules,'scientific_rubric':rubric,'reference_stage':status,'calibrated_expanded_tolerances':None,'scoring_notes':['Not release-certified; expanded numeric references and method-dependent uncertainty are pending. Never issue an upgraded scientific PASS from these structural tests.','Each item receives credit only for verified scientific evidence. Correct format or an honest failure earns no uncomputed endpoint credit. Missing core comparison prevents scientific completion regardless of total points.','Experimental input uncertainties constrain only their corresponding measured observables. Old final numeric tolerances are archived, not applied to the expanded matrix.','Invalid identity, spin, energy reference, fabricated evidence or borrowed results invalidate dependent conclusions. Valid collapse/refutation/indistinguishability remains eligible with complete evidence.','No optional extension is a hard-failure condition.']}
 failures=[('old_scalar','Only the legacy scalar/spectrum/geometry with no new required comparison.'),('missing_core','A required matrix row/contrast has no actual computation or valid mapped collapse evidence. Calling it uncertain does not complete it.'),('wrong_identity','Wrong graph, atom inventory, charge/multiplicity, isomer, state or medium; cross-composition or cross-state totals compared without a balanced reference.'),('wrong_zero','Uses an energy definition other than '+ref(pid)+' without an explicitly recomputable equivalent transformation.'),('false_completion','Failure, absent raw outputs, synthetic numbers, copied author values or historical PASS presented as completed new science.'),('unsupported_inference','A local molecular proxy asserted to prove a rate, yield, device, aggregate or bulk property outside the stated boundary.'),('invalid_control','Constrained point presented as a free minimum, missing state/path validation, or unlike fragments/thermochemistry silently mixed.')]
 if s['block']:failures.append(('unresolved_input_block',s['block']+' No scientific complete status until resolved in a new reviewed package.'))
 evals['critical_failures.json']={'paper_id':pid,'items':[{'failure_id':k,'description':v,'effect':'invalidate dependent scientific claim; missing core prohibits scientific completion'} for k,v in failures]}
 evals['evidence_map.json']={'paper_id':pid,'evidence':[{'evidence_id':'source_main_si','source':sources,'description':s['source'],'scope':'Original publication facts and method only. Source optimized endpoints remain private; no expanded validation claimed.'},{'evidence_id':'benchmark_design','source':{'path':'evaluation/reference_validation_plan.md','kind':'new_benchmark_control_design'},'description':s['objective'],'scope':'Expanded controls pending scientific reference calculation.'}]}
 plan='# Expanded reference validation plan\n\nStatus: **'+status+'**. New quantum-chemical calculations performed in this development turn: **0**. Graph/count checks and schema fixtures are not scientific reference validation.\n\n## Source material inspected\n\n'+s['source']+'\n\n'+ '\n'.join('- `'+x['path']+'` SHA-256 `'+x['sha256']+'`' for x in sources)+'\n\n## Scientific definitions and original route\n\n'+s['boundary']+'\n\n'+s['author']+'\n\n## Reusable legacy evidence\n\n`legacy_final_snapshot/` contains byte-exact original tasks, public input and evaluator snapshots with source hashes. Only like-defined original object checks, measured input data and documented baseline methods may be reused. Historic PASS and old tolerances do not establish expanded coverage. Consult the source-guide record in `task_provenance/upgrade_audit.json` for baseline discrepancies.\n\n## Minimum pilot\n\n'+s['pilot']+'\n\n## Minimum complete reference\n\n'
 for p in s['panels']:plan+='- '+p['name']+': '+', '.join(p['rows'])+'. '+p['criterion']+'\n'
 plan+='\n## Available software and resource boundary\n\n'+asgn['software']+'. Capability is based on chemistry_toolbox/README.md, config/native_software_guides.yaml and config/mcp_profiles.yaml. Gaussian/ORCA native input is allowed where a specialized Action is absent; CREST/xTB is a preparation aid, not a replacement DFT endpoint. Check exact functional, dispersion, ECP/solvent and analysis conventions. No new software installation, paid service, long scientific job or HPC was launched. Pilot costs and complete expanded reference costs remain unmeasured.\n\n## Reference gap and release gate\n\nAll expanded matrix energies/properties, validated stationary states/paths, alternate-method or conformer uncertainty and independent agent trial remain to be calculated. Numerical acceptance intervals must be frozen from actual matched references, convergence, conformer/model variability and experimental extraction error. Absolute and relative observables need separate calibration. Do not inherit a narrow legacy +/- range or set a new range to make failing objects pass. Before release run complete positive, refutation/indistinguishability, old-only, missing-core, wrong-object/spin/zero and false-completion replays using genuine artifacts. Current batch tests only exercise package, schema and export boundaries.\n\n'
 if s['block']:plan+='## Verified blocker\n\n'+s['block']+'\n\n'
 plan+='## Optional boundary\n\n'+s['optional']+'\n'
 guide='# Submission guide\n\nUse `report/results.json` and `report/report.md`. The schema defines the exact core matrix; no universal free-text result can replace it.\n\n'+s['boundary']+'\n\n'
 guide+='`object_records` gives validated charge/spin/graph/geometry mappings for every object used. `calculation_records` links each actual job to raw input/output; successful engine jobs require actual geometry, energy and convergence evidence. Density-analysis records require their actual input/output and validation evidence, without inventing a new geometry or electronic energy. All IDs in results must resolve to these records. Each required row names `calculation_ids`, `atom_map_file`, `raw_files`, `data_table_file`, and numeric `metrics`; tables contain all states/angles/conformers, not just extrema. Evaluators open these files.\n\n'
 guide+='A prerequisite failure before engine launch may use empty object_records and calculation_records and zero allocated_cores/engine_starts/core_hours, with real diagnostic raw_files and failure_report. Protocol fields describe intended settings and explicitly identify unused software. Do not invent geometry, frequency, energy or job evidence. Complete submissions retain every scientific endpoint and require at least one successful engine record; density analysis alone is insufficient.\n\n'
 for p in s['panels']:guide+='- `results.'+p['name']+'`: mandatory rows '+', '.join(p['rows'])+'; numeric metrics '+', '.join(p['metrics'])+'. '+p['criterion']+'\n'
 guide+='\nRow-specific metric applicability in the schema and scientific criteria takes precedence over the generic numeric metric list. Required nulls with an explanation identify quantities that do not exist for that object; they never excuse a missing applicable computation.\n\nProvide two real `hypothesis_tests`, an actual quantitative `sensitivity` pair and a bounded `conclusion`. The `core_matrix_complete` flag is a claim to verify, not self-certification. An `evidenced_collapse` row needs two or more raw artifacts and a mapped retained endpoint; its table must establish a real basin/identity mapping. It cannot replace a missing method calculation, failed job or aggregate comparison.\n\nUse `partial` or `bounded_failure` with `failure_report` and actual diagnostics for unfinished work. Such submissions are accepted for audit but do not meet scientific completion. `complete` requires every core row and at least one successful real job; the scientific evaluator additionally verifies all required jobs, objects, states, arithmetic and files.\n\nResource times and starts are measured, not inferred from work-package count. Engine time, summed jobs and elapsed calendar time are separate. Optional work receives no required fields or mandatory failure tests. All synthetic regression fixtures are temporary format-only data and must not be submitted as research.\n'
 if s['block']:guide+='\n**Blocked development contract:** only partial/bounded_failure status is accepted. '+s['block']+'\n'
 for mode in ['autonomous_research','paper_reproduction']:
  root=D/mode/pid;inp=root/'agent_input';ev=root/'evaluation'
  # Retire inherited active validation claims, preserve exact copies under private snapshots.
  for p in list(ev.rglob('*')):
   if p.is_file() and 'legacy_final_snapshot' not in p.parts and p.name!='upgrade_audit.json':p.unlink()
  (inp/'task.md').write_text(title+(guidance if mode=='paper_reproduction' else '')+core)
  dump(inp/'submission_schema.json',contract);(inp/'submission_guide.md').write_text(guide)
  for name,x in evals.items():dump(ev/name,x)
  (ev/'reference_validation_plan.md').write_text(plan)
  (ev/'verified_computation_reference.md').write_text('# Development reference status\n\nNo expanded scientific reference has been certified. Status: '+status+'.\n\nSee `reference_validation_plan.md` and private `legacy_final_snapshot/` for historical material. The old PASS does not apply. New quantum calculations: 0.\n')
  docs=['docs/evalution/update/'+pid+'.md','docs/evalution/update/upgrade_implementation_guide_20260927.md','docs/evalution/update/upgrade_guidance_review_20260927.md','docs/evalution/update/upgrade_guidance_review_manifest_20260927.json'];docs=[x for x in docs if (ROOT/x).exists()]
  legacy=next(x for x in json.load(open(B/'evidence/legacy_run_review.json')) if x['paper_id']==pid)
  audit=json.load(open(ev/'task_provenance/upgrade_audit.json'));audit.update({'implementation_date':'2026-09-27','batch':3,'source_docs':[{'path':p,'sha256':sha(ROOT/p)} for p in docs]+sources,'old_class':asgn['current_class'],'new_class':asgn['target'],'status':status,'new_scientific_calculations_performed':False,'new_scientific_engine_starts':0,'scientific_reference_validated':False,'blocker':s['block'],'input_preparation':'Mapped graph extraction and formula/charge checks only; source optimized coordinates are not public new answers.','first_version_spec':asgn['first_version_spec'],'reference_gaps':['All new core matrix numeric references','Stationary-state/path validation','Method/conformer uncertainty calibration','Independent upgraded trial'],'source_evidence_read':s['source'],'source_baseline_gate':asgn['gate'],'historical_evidence_review':legacy['historical_result_files_read']});dump(ev/'task_provenance/upgrade_audit.json',audit)
  info=json.load(open(root/'task_info.json'));info.update({'title':s['title'],'difficulty':'hard','difficulty_reasons':[s['objective'],'Expanded reference calibration pending; require actual core control evidence.'],'data':[{'path':'data/inputs','description':'Finite atom-mapped molecular objects, intervention definitions and authorized source experimental inputs.'}],'required_deliverables':[{'path':'report/results.json','description':'Structured expanded matrix and raw-evidence links.'},{'path':'report/report.md','description':'Readable scientific report with counterevidence, robustness and limitations.'}]});dump(root/'task_info.json',info)
  if (root/'paper_route.md').exists():(root/'paper_route.md').write_text('# Private development paper route\n\n'+s['author']+'\n\n## Expanded first-version scope\n\n'+s['objective']+'\n\n'+s['boundary']+'\n\n## Status and evidence\n\n'+status+'. '+s['source']+'\n\n'+(s['block'] or 'Expanded reference computations and uncertainty calibration pending.')+'\n\nThe original route and numeric anchors are archived in evaluation/legacy_final_snapshot/paper_route.md.snapshot; they do not certify the new endpoints.\n')
  entries=package_payload_entries(root);manifest=PackageManifest(paper_id=pid,task_type=mode,entries=entries,package_content_sha256=package_content_hash(entries));dump(root/'package_manifest.json',manifest.model_dump(mode='json'))
 return {'paper_id':pid,'old_class':asgn['current_class'],'new_class':asgn['target'],'status':status,'AR':str((D/'autonomous_research'/pid).relative_to(ROOT)),'PR':str((D/'paper_reproduction'/pid).relative_to(ROOT)),'blocker':s['block'],'scientific_upgrade':s['objective'],'reference_gaps':['expanded core reference matrix','stationary/path/state checks','uncertainty and pilot resource calibration','independent upgraded execution'],'source_locator':s['source'],'new_scientific_calculations_performed':False,'checks':'pending batch validation'}

def status(records):
 done={x['paper_id']:x for x in records};text='# 第 3 批升级状态\n\n2026-09-27。任务包开发，不等同新增科学参考验证；新增量化计算为0。\n\n'
 for pid in A['batch']['papers']:
  if pid not in done:text+='- '+pid+'：进行中（科学输入/契约同步）\n'
  else:text+='- '+pid+'：'+done[pid]['status']+'；AR/PR科学、公开输入、schema及五份evaluator已同步。'+(done[pid]['blocker'] or '扩展科学参考待计算。')+'\n'
 (B/'STATUS.md').write_text(text)
if __name__=='__main__':
 rows=[]
 for pid in A['batch']['papers']:
  rows.append(implement(pid));status(rows);dump(B/'manifest.json',{'batch':3,'date':'2026-09-27','papers':rows,'new_scientific_calculations_performed':False});print(pid,rows[-1]['status'],flush=True)
