"""Paper-specific development specifications. No computed reference values are stored here."""
S={}
def add(pid,title,objective,boundary,author,source,pilot,panels,optional,block=None):
 S['paper_'+pid]=dict(title=title,objective=objective,boundary=boundary,author=author,source=source,pilot=pilot,panels=panels,optional=optional,block=block)
def panel(name,rows,metrics,criterion):return dict(name=name,rows=rows,metrics=metrics,criterion=criterion)
# A row is a named required comparison, not a request for an unrestricted results blob.
add('36722b90a0c12825','E/Z chloride binding and conformational preorganization',
 'Determine whether E/Z photoisomerization changes chloride affinity through host preorganization, host distortion, or the common solvent environment. Test a closed binding cycle for the (1,3)Ph host rather than infer affinity from two bound E conformers.',
 'Use the complete C48H26F12N14 host: E and Z each free (charge 0, singlet) and with one chloride (charge -1, singlet), plus Cl- (singlet). Ac means acetone, not acetonitrile. Primary solution boundary: acetone, 298.15 K, 1 M standard state; convert any 1 atm RRHO terms explicitly. Sum over distinct validated conformers within each E/Z family, not between photostationary E and Z populations. TBA+ is a counterion context; an explicit TBACl sensitivity must use balanced composition. A second host is a separately chosen optional transfer check.',
 'The authors associate triazole preorganization and cavity accessibility with light-switchable chloride binding. They use Gaussian 16 B3LYP/6-31G*, D3(BJ), PCM acetone/UFF cavity, harmonic corrections at 298.15 K and counterpoise treatment of binding. Their (1,3)Ph titration constants overlap in uncertainty; the strong-switch claim must not be imposed on this host. The complete E/Z ensemble cycle and geometry/environment interventions below are benchmark extensions, not a claim that the source validated them.',
 'Main PDF pp3-4 Figs3-5; coordinate SI1 pp2-8; SI2 pp6-7,15-16, Table S2 and DFT section.',
 'Audit E/Z N=N stereochemistry, all 100 host atoms and chloride charge; independently reproduce one free/bound pair, then a host distortion term. Old G(open)-G(close) and electronic E(open)-E(close) are different observables and neither is a binding switch.',
 [panel('species_ensembles',['E_free','E_bound','Z_free','Z_bound','chloride'],['electronic_energy_Eh','ZPE_Eh','thermal_correction_Eh','G_1M_Eh'],'Validate minima and conformer coverage for all four chemical states; isolate electronic, ZPE, thermal and concentration corrections. Include conformer weights and all attempted structures in raw tables.'),panel('binding_cycle',['E_bind','Z_bind','Z_minus_E'],['delta_G_kJ_mol','delta_E_kJ_mol','conformational_cost_kJ_mol'],'Recompute G(host.Cl)-G(host)-G(Cl) for each family and DeltaDeltaG=DeltaGbind(Z)-DeltaGbind(E). Report interaction and distortion with compatible fragment geometry and BSSE conventions.'),panel('intervention',['frozen_host','solvent_or_ion_pair'],['primary_contrast_kJ_mol','control_contrast_kJ_mol','change_kJ_mol'],'At least one frozen/relaxed host contrast and one actual solvent/counterion sensitivity must challenge the interpretation. Do not use PSS as Boltzmann population.')],
 'Complete titration fitting, exact PSS composition and device switching efficiency are optional and unscored.')
add('9455a82229de2427','SiN–isoprene candidate and path discrimination',
 'Identify a finite, defensible set of cyclic SiNC5H7 products and distinguish thermodynamic compatibility from dynamical accessibility under a single collision.',
 'Reactants SiN (0, doublet) and isoprene C5H8 (0, singlet) produce SiNC5H7 (0, singlet) plus H (0, doublet). Doublet SiNC5H8 addition/rearrangement structures share the reactant atom map. Use separated reactants as zero for E0=Eelectronic+ZPE at 0 K. Collision energy 25±1 kJ/mol and experimental channel exoergicity -162±27 kJ/mol are observations, not computed answers. Enumerate terminal-C1/C4 attack by Si and N, then at least ring closure and H-loss alternatives. Declare explored bond edits and remaining search limits.',
 'The source uses Gaussian 16 CBS-QB3 and a finite reaction PES; terminal addition, rearrangement, ring closure and H elimination motivate cyclic products. Published channels include two methylazasilacyclohexadienylidenes. They are hypotheses for PR, not compulsory winners. The benchmark additionally requires a main and an energetically competitive connected route with equal zero and explicit spin bookkeeping; full scattering/RRKM is not assumed.',
 'Main PDF pp3-8 computational details, Fig3 energy distribution and reaction PES; SI p2 Table S1 and pp3-15 CBS-QB3 coordinates/energies.',
 'Validate one atom-conserving doublet route and H-loss asymptote with endpoints before freezing any barrier threshold. A TS requires mode and bidirectional connection, and a barrierless route requires a continuous converged path.',
 [panel('candidate_space',['terminal_C1_Si','terminal_C4_Si','terminal_C1_N','terminal_C4_N'],['lowest_E0_kJ_mol','product_reaction_E0_kJ_mol'],'Provide mapped graph-edit enumeration, attempted structures, state validity and products for the four attack families. Multiple seeds collapsing to one product are legitimate only with raw mapped evidence; no requirement for four distinct products.'),panel('connected_routes',['main_route','competitor_route'],['maximum_relative_E0_kJ_mol','reaction_E0_kJ_mol','collision_margin_kJ_mol'],'Submit ordered mapped nodes/edges, optimized endpoints, TS and IRC files or continuous no-barrier path evidence. Recompute all nodes relative to SiN+isoprene, including the free H atom.'),panel('accessibility',['thermodynamic_vs_kinetic','method_sensitivity'],['main_minus_competitor_kJ_mol','uncertainty_kJ_mol'],'Separate lowest-energy product, channel exoergicity and accessible barrier. Compare collision margins and demonstrate method/ZPE sensitivity; no 298 K equilibrium abundance or branching ratio inference.')],
 'Full scattering, exact branching ratios and a complete RRKM network are optional.')
add('9a58a1fa6ed7d780','BN incorporation versus geometry in matched fluoranthenes',
 'Test whether BN incorporation changes state energies and charge separation beyond geometry and method uncertainty, using matched BN-AkFlu and CC-AkFlu graphs.',
 'BN-AkFlu 5a is C22H14B2N2 (40 atoms in the supplied actual graph), not the H15 typo in an old route. CC-AkFlu 5b is C26H14, 40 atoms, from SI Table S22. Both are neutral singlets in gas phase. Use each relaxed geometry and cross-evaluate on a common mapped heavy-atom scaffold; replacing B/N by C is a chemical intervention with changed nuclear charges. Track physical states via NTO/density overlap, not root numbers alone; retain six vertical roots and descriptors for the first four source baseline roots.',
 'The authors use Gaussian 16 B3LYP/6-311G(d,p) and Multiwfn to associate internal BN doping with changed frontier levels, weak low-energy absorption and higher bright states. SI Tables S11/S14/S21/S22 provide descriptors, transitions and geometries. Frozen cross-scaffold comparisons and analysis convergence controls are new benchmark tests. Existing S1-S4 Sr fields were present; old S1 energy/S4 overlap disagreement is a calibration issue.',
 'Main pp2-4 Figs2-3; SI p3 methods, Tables S11/S14 and pp49-51 Tables S21-S22.',
 'Recheck BN stoichiometry, S1 energy, S4 Sr, root mapping and full TD amplitudes; compare normalized hole/electron grids before expanding the all-carbon control.',
 [panel('relaxed_states',['BN_relaxed','CC_relaxed'],['matched_excitation_eV','oscillator_strength','D_A','Sr'],'Preserve full S1-S6 table and S1-S4 density-analysis raw data. Sr is integral sqrt(rho_h*rho_e) over space for normalized densities; D is centroid separation.'),panel('common_scaffold',['BN_on_CC','CC_on_BN'],['matched_excitation_eV','oscillator_strength','D_A','Sr'],'Map the common framework and show both cross geometries. Frozen points are not optimized minima. Use NTO/transition-density mapping to avoid claiming a root switch as a direct chemical shift.'),panel('attribution',['chemical_effect','geometry_effect','analysis_convergence'],['excitation_change_eV','D_change_A','Sr_change'],'Recalculate paired changes and analysis-grid/amplitude sensitivity independently of excitation-energy convergence. Accept a mixed or unresolved BN effect if all controls are computed.')],
 'New-molecule screening, quantum yield, charge mobility and bulk packing claims are excluded.')
add('9f4c259696ad2f87','Lewis-acid stoichiometry and PXX optical response',
 'Discriminate pi-extension, molecular distortion and Lewis-acid coordination as explanations of PXX optical shifts while testing whether spectra identify a unique acid stoichiometry.',
 'Use PXX1 C43H28O3 and PXX2 C50H30O4, neutral singlets; acid is neutral B(C6F5)3. Each PXX has 0, 1 and 2 acid units; PXX1 has one carbonyl, so its second acid explores the available ether/carbonyl-site competition as a new candidate, not an asserted second independent ketone. PXX2 has two carbonyls. All whole complexes are neutral singlets. CH2Cl2 is the shared primary medium. Compare sequential acid association reactions, never bare total energies of different acid counts. Use 298.15 K and 1 M as explicit development thermochemistry conventions; no equilibrium population is inferred without concentration evidence.',
 'The authors propose enhanced carbonyl acceptor strength and PXX-to-ketone/acid charge transfer. Gaussian 16 B3LYP/6-31G(d) PCM(CH2Cl2) is described in SI methods; the main Fig7 caption states 6-311G(d), which must be disclosed as a source discrepancy. SI p167 reports a single titration equivalence point for two-ketone compound 2 and explicitly leaves one/two site occupancy ambiguous. The full 0/1/2 matrix and frozen acid-removal controls below extend the source.',
 'Main pp8-10 Figs6-7; SI pp5-6 methods, pp144-149 coordinates, pp167-169 Lewis adduct discussion.',
 'Pilot the largest two-acid model, verify carbonyl versus ether atom map and state tracking, then calibrate sequential association and fixed-geometry acid removal. Do not assume all large adducts are stable minima.',
 [panel('stoichiometric_series',[f'{p}_acid{n}' for p in ['PXX1','PXX2'] for n in [0,1,2]],['G_Eh','excitation_eV','oscillator_strength','CT_distance_A'],'Require actual conformer/site attempts, stoichiometric identities and matched transition densities for every acid count; evidenced dissociation/collapse is reportable.'),panel('balanced_binding',[f'{p}_step{n}' for p in ['PXX1','PXX2'] for n in [1,2]],['delta_G_kJ_mol','interaction_kJ_mol','distortion_kJ_mol'],'Recompute PXX.acid_n minus PXX.acid_(n-1) minus free acid with common thermochemistry and 1 M correction. Demonstrate composition balance and conformer effects.'),panel('geometry_and_spectrum',['PXX1_acid_removed','PXX2_acid_removed','titration_discrimination'],['excitation_change_eV','oscillator_strength_change','uncertainty_eV'],'Remove acid at the same PXX geometry and compare independently relaxed PXX; compare observed trend without forcing unique occupancy from similar spectra. Preserve digitization/concentration limits.')],
 'FRET, full concentration dynamics and absolute emission efficiency are outside the core.')
add('a0f6b899582cb9f7','M3 donor and acceptor fragment interactions',
 'Test whether M3 has comparable evidence for interaction with PM6 and BTP-eC9 fragments and whether apparent attraction arises from electrostatics, dispersion or distortion.',
 'M3 is neutral singlet 2,5-di(thiophen-2-yl)pyrazine C12H8N2S2. The source identifies PM6 (BDD region) and BTP-eC9 (core/end region), not an unspecified generic acceptor. A finite source-grounded donor fragment, acceptor fragment, exact cap bonds and one enlarged fragment are required before any calculation can be considered a defined comparison. No arbitrary fragment replacement is authorized.',
 'The authors propose a planar N...S-locked quadrupolar additive with affinity for donor BDD and acceptor BTP-eC9 regions. Main Fig1 shows pair models; source M3 DFT is B3LYP/6-31G. Pair energy decomposition and matched truncation controls are new. The printed quadrupole unit D is not a canonical quadrupole unit; use a declared origin and e angstrom squared or properly converted atomic units.',
 'Main p2 Fig1 and pp3-4 interactions; SI pp3,5 molecular characterization and FigS3; no atom-resolved PM6/BTP-eC9 fragment coordinate/cap list was found in these materials.',
 'Resolve both capped fragment graphs and enlarged counterpart against Fig1, then pilot one pair and SAPT feasibility. An alternative decomposition requires a stated, calibrated definition, not renaming unlike components.',
 [panel('contact_models',['PM6_face','PM6_edge','BTP_core_face','BTP_core_edge'],['interaction_kJ_mol','distortion_kJ_mol'],'Each pair requires complete graph, contact map and several starting orientations at fixed composition; compare released versus frozen fragments.'),panel('decomposition',['PM6_pair','BTP_pair'],['electrostatic_kJ_mol','dispersion_kJ_mol','exchange_kJ_mol','induction_kJ_mol'],'Use a single justified decomposition and identical fragmentation; terms are model-dependent, not unique causal observables. Recompute total and residual terms.'),panel('truncation_and_tensor',['larger_fragment','M3_tensor'],['primary_interaction_kJ_mol','control_interaction_kJ_mol','quadrupole_zz_eA2'],'At least one actual larger-fragment pair is core. Report all six independent tensor components with origin/axes; Qzz alone cannot prove dual binding or PCE.')],
 'Bulk blend morphology and device simulations are optional.',
 'blocked_input_definition: Main Fig1 identifies PM6/BTP-eC9 but the available SI contains no atom-resolved capped pair models. Exact cut bonds, caps, charge validation and enlarged matched fragments remain unverified. Release requires independently checked full mapped fragment graphs and a truncation-pair pilot; M3 alone is insufficient.')
add('b276b18215cba283','Transfer of single-arm conformational shifts to three arms',
 'Test whether the single-arm conformational optical shift survives in the full three-arm chromophore, and distinguish arm geometry from inter-arm electronic mixing.',
 'Use the neutral singlet single-arm C26H27NO3 and complete three-arm C66H69N3O3 graphs. Cisoid/transoid are mapped torsional families on each exocyclic arm, not a change of composition. Primary gas-phase calculations permit direct comparison with the source; a common ethanol continuum is the environment sensitivity, not a model of a membrane. Each full-model result requires arm partitions and matched transition densities.',
 'SI FigsS12-S13 and Tables S8-S11 use CAM-B3LYP/6-31G(d,p), Gaussian16, and compare transoid/cisoid S0 geometries and low singlet states. Authors propose this shift as one contributor to the long-wavelength quatsome absorption. Frozen-arm cross-model and medium controls below are new; linear TDDFT does not establish two-photon brightness or membrane aggregation.',
 'Main pp4-5 optical/quatsome discussion; SI pp15-16 FigsS12-S13, pp45-64 Tables S8-S11.',
 'Confirm complete 141-atom three-arm graph and three arm maps, then pilot full TD root window/cost. Without at least one complete three-arm electronic result there is no transfer conclusion.',
 [panel('relaxed_models',['single_transoid','single_cisoid','three_transoid','three_cisoid'],['excitation_eV','oscillator_strength','G_Eh'],'Retain at least four low roots in the three-arm model with NTO and arm-resolved transition-density fractions; do not equate root labels across models.'),panel('arm_geometry_control',['single_on_three_transoid','single_on_three_cisoid','three_fixed_arm'],['excitation_eV','oscillator_strength','interarm_transfer_fraction'],'Extract mapped arm from full geometry under a declared cap rule; compare frozen and relaxed arm and complete model. Preserve graph/partition/constraint files.'),panel('transfer_and_medium',['gas_transfer','ethanol_transfer'],['single_shift_eV','three_shift_eV','difference_eV'],'Quantify whether transfer survives medium, state mapping and method/conformer uncertainty; actual full-model data are mandatory. No membrane or two-photon mechanism inferred.')],
 'Two-photon cross sections, membrane aggregates and absolute lifetimes are optional.')
add('fda8b9b53f8276db','Cis/trans quinoxaline geometry and environment',
 'Determine whether local bond residuals and cis/trans preference are attributable to torsional conformation or medium, keeping the original six-bond cis validation separate from thermochemistry.',
 'Use neutral singlet 6,7-dimethyl-2-(pyridin-2-yl)quinoxaline, C15H13N3, from CCDC2433822. Cis/trans is the mapped N1-C1-C2-N2 torsion; preserve deposited labels. Primary gas phase and acetonitrile continuum at 298.15 K, consistent 1 M molecular convention for solution. Six bonds are exactly those in experimental_bonds.json; seven SI or 33 CIF bond sets must not enter this RMSE.',
 'The authors compare a gas-phase cis local minimum with crystal intramolecular bonds using Gaussian03 B3LYP/6-311+G(2d,p). The crystal pyridyl orientation differs; a local minimum need not be globally lowest. The paired cis/trans solvent and torsion controls are benchmark extensions.',
 'Main p4 computational structure discussion; SI Table S2 and FigsS11-S13; immutable CCDC2433822 and current final experimental_bonds.json define the six-bond scope.',
 'Recover the current cis six-bond baseline and N1-C1-C2-N2 mapping, not a historical trans/seven-bond result; then validate both environments and one restrained torsion.',
 [panel('conformer_environment',['cis_gas','trans_gas','cis_MeCN','trans_MeCN'],['electronic_Eh','G_Eh','torsion_degree'],'Validate graph/minima, searches and environment-specific conformer identity; a released candidate may merge into another basin with actual evidence.'),panel('six_bond_residuals',['cis_gas','trans_gas','cis_MeCN','trans_MeCN'],['C1_C2_A','C2_C3_A','N1_C1_A','N2_C2_A','N3_C3_A','C1_C10_A','RMSE_A'],'Recompute six unrounded residuals and RMSE against the authorized experimental distances. Separate any larger bond statistics; include OLS with intercept only if called R squared.'),panel('torsional_intervention',['gas_fixed_vs_relaxed','MeCN_fixed_vs_relaxed'],['torsion_degree','delta_E_kJ_mol','residual_change_A'],'A defined mapped torsion restraint and relaxed counterpart distinguish geometric from solvent effects. Nonstationary restrained points receive no borrowed harmonic G.')],
 'CIF neighbor clusters, solid-state explanation and NMR are optional.')
add('0de37d01e35c27df','Oxidation and transannular sulfur bonding controls',
 'Test whether oxidation-induced sulfur approach is accompanied by the occupation, spin and bonding changes required for a two-center three-electron interpretation.',
 'Use the exact mapped norDTCO C10H14S2 graph already supplied, with S16/S17, and source DTCO (1,5-dithiacyclooctane C6H12S2) as the rigidity control. Each neutral is charge 0 singlet and radical cation charge +1 doublet. Compare each at its own relaxed backbone and vertically on the other oxidation-state geometry in gas phase. A geometric S...S contact is not a covalent edge in the starting neutral graph.',
 'The source proposes sulfur-centered oxidation and 2c-3e interaction; main Fig2 and SI Tables S3/S4/S7/S8 use BP86/TZVP Gaussian16 (unrestricted for radicals). It also discusses distinct dications, which are not the one-electron oxidation target. Cross-geometry and orbital-occupation controls below extend the baseline.',
 'Main pp3-4 Fig2/Table1; SI pp10-11 TablesS3/S4, pp15-18 TablesS7/S8 and orbital/EPR sections.',
 'First fix norDTCO topology/charge and reject spurious S-S bonds inferred by distance alone. Validate one neutral/cation pair and the DTCO ring graph before correlating contraction with bonding.',
 [panel('oxidation_pairs',['nor_neutral','nor_cation','DTCO_neutral','DTCO_cation'],['SS_distance_A','electronic_Eh','spin_S_total','bond_order'],'Require valid structures, unrestricted spin diagnostic, natural/SOMO occupations and density/bond analysis. Bond order definition must be consistent across both topologies.'),panel('vertical_geometry',['nor_cation_on_neutral','nor_neutral_on_cation','DTCO_cation_on_neutral','DTCO_neutral_on_cation'],['SS_distance_A','electronic_Eh','bond_order','antibonding_occupation'],'Pair fixed backbone and relaxed state evidence to separate mechanical contraction from electronic bonding. Retain same atom map.'),panel('bonding_interpretation',['rigidity_contrast','analysis_sensitivity'],['contraction_difference_A','bond_order_change','occupation_change'],'Compare contraction against orbital occupation/spin localization and independent density evidence. A short distance without electronic support weakens the hypothesis; ring opening must have a new topology ID.')],
 'Dication chemistry, full aryl series and electrochemical reversibility are optional.')
add('43d74f8a469d9ad3','Mapped ground and excited torsion in boron dyes',
 'Test whether restriction of the same aryl rotation changes S0/S1 energetics and transition character across two source boron dyes, distinguishing geometric restriction from chemical substitution.',
 'Core comparison: Scheme1 compound1 C23H20BNO3 and compound2 C24H22BNO4, neutral singlets. Compound1 is fixed by CCDC2441197; compound2 adds the para-to-phenoxy methoxy group shown in Scheme1, retaining the 3,5-dimethylphenyl boron substituent. Use mapped X-B-Cipso-Cortho on that aryl branch in both. Primary gas phase and an explicitly identical optical solvent sensitivity. Source SI coordinate labels S5/S6 conflict with Scheme1 identities; their unchecked coordinate assignments are not authorized.',
 'The source proposes steric shielding/restricted rotation; its torsion subsection uses PBE0/def2-SVP and a 24-point ground-state scan, while general TD calculations use M06-2X/6-311++G(d,p). These are distinct source protocols. The benchmark adds state-tracked S1 scans and relaxed/restrained comparison; a ground-state scan maximum is not a transition state and does not predict bleaching rates.',
 'Main p2 Scheme1, pp3-4 computational section, pp8-10 torsion/photostability; CCDC2441197. SI pp32-37 Tables S5-S8 contain composition/label inconsistency.',
 'Map the actual CCDC boron aryl branch and Scheme1 methoxy substitution; validate continuous S1 state tracking on one short torsion segment before completing a scan.',
 [panel('torsion_profiles',['dye1_S0','dye1_S1','dye2_S0','dye2_S1'],['torsional_range_kJ_mol','reference_angle_degree','tracked_excitation_eV'],'Store a numeric angle-energy-property CSV with mapped atoms at each point, constrained degrees of freedom and forward/backward state overlap; include released anchors.'),panel('restriction_control',['dye1_restricted_vs_free','dye2_restricted_vs_free'],['excitation_change_eV','oscillator_strength_change','relaxation_kJ_mol'],'Use the same mapped angle intervention in both compounds, with actual frozen and relaxed calculations. Root switching is recorded, not smoothed away.'),panel('continuity_and_robustness',['state_following','method_or_grid'],['minimum_state_overlap','energy_change_eV','profile_change_kJ_mol'],'Demonstrate TD root-window/step-size or method sensitivity and identify discontinuities. Do not extrapolate S0 resistance to an absolute photobleaching rate.')],
 'Nonadiabatic trajectories, conical intersections and absolute lifetime prediction are optional.')
add('86a0b654270a8ce7','Ir–salen isomer thermochemistry and stacking',
 'Determine whether the relative stability of two Ir–salen–NHC coordination isomers survives conformational, low-frequency and method controls and whether stacking offers a supported local explanation.',
 'Both complete IrC60H63N4O2 isomers are neutral singlets, in THF at 339 K. Preserve Ir coordination identity; report E, solvent contribution, ZPE/thermal and low-frequency correction separately with one standard state. The source predicts a preference, but a contrary converged method is not discarded. Contact-separation restraints measure interaction plus deformation and must not be called pure pi-stacking energies.',
 'The authors use Gaussian16 B3LYP/def2SVP SMD(THF), 339 K and propose isomer2 stabilization from intramolecular stacking. Their isolated yield ratio was compared to a Boltzmann ratio, but without demonstrated interconversion that is not an equilibrium validation. The new ensemble, contact-intervention and method controls test rather than assume the source interpretation.',
 'Main pp2-3 Scheme1 thermochemistry and contact discussion; SI pp6-7 geometry and pp11-18 Gibbs calculation details/coordinates.',
 'Resolve the old reversed ranking with exact isomer labels and E/G decomposition. Pilot a released conformer of each plus a fixed-contact intervention; preserve negative method results.',
 [panel('isomer_ensembles',['isomer1','isomer2'],['electronic_Eh','solvation_Eh','thermal_Eh','low_frequency_Eh','G_339K_Eh'],'Use low-energy conformer coverage and frequency evidence with identical 339 K convention; reconstruct ensemble G and document degeneracy.'),panel('stacking_intervention',['isomer1_contact','isomer2_contact'],['centroid_distance_A','relative_angle_degree','delta_E_kJ_mol','distortion_kJ_mol'],'Submit mapped aromatic ring atoms and frozen/released contacts, controlling other geometry. Distortion cannot be removed by merely labeling the difference stacking.'),panel('ranking_robustness',['method_change','thermal_model_change'],['delta_G_2_minus_1_kJ_mol','uncertainty_kJ_mol'],'Quantify sign and interval under actual methods and thermal treatment; unresolved ranking after complete data is acceptable. Isolated yields are not a scored equilibrium ratio.')],
 'Complete interconversion networks and exact isolated yields are optional.')
add('94e7481ded3b6a75','Local motion and excitation in BN-anthracene',
 'Test the molecular contribution of constrained motion to BN-anthracene excitation and charge transfer, separating a local geometry effect from an unsupported aggregate explanation.',
 'First version uses source PBNA C24H22B2N2, neutral singlet, with the two mapped B-phenyl torsions. Compute S0 and a tracked S1 on released and identically restrained motion coordinates, primary gas phase with common CH2Cl2 sensitivity. A restrained excited-state point is an intervention, not an unconstrained S1 minimum. Retain all B/N connectivity.',
 'The authors use Gaussian09 B3LYP/6-31G(d) for PBNA and functionalized BN-anthracenes and discuss orbital distribution, solution optics and aggregation-induced behavior. The source ground-state PBNA endpoints do not validate excited motion. S1 motion intervention and state matching below are new. No single-molecule evidence proves a crystal AIE mechanism.',
 'Main pp4-6 Fig3/Fig4; SI pp16-19 aggregation/optical context and p19 TablesS11-S12 ground-state methods/coordinates.',
 'Validate one PBNA S1 and one mapped B-phenyl restraint, checking root continuity and excitation gradients before interpreting a motion effect.',
 [panel('state_geometry',['S0_free','S1_free','S0_restrained','S1_restrained'],['electronic_Eh','torsion_degree','excitation_eV','oscillator_strength'],'Keep geometric and electronic-state records distinct; S1 and S0 energies must refer to the stated same protocol and geometry.'),panel('motion_response',['vertical_fixed_motion','relaxed_motion'],['excitation_change_eV','CT_distance_change_A','relaxation_kJ_mol'],'Inspect NTO/transition densities and local geometry; compute paired effects rather than infer them from frontier orbital pictures.'),panel('local_robustness',['second_torsion_or_method','common_solvent'],['primary_effect_eV','control_effect_eV','uncertainty_eV'],'Actual motion/method or medium sensitivity bounds the isolated-molecule claim; no quantum yield, knr or bulk AIE is scored.')],
 'Dimers, crystal AIE, nonradiative rates and quantum yields are optional.')
add('9aa6d5655edfeb52','Carborane fusion and cage-motion response',
 'Discriminate arene fusion from cage motion as explanations of state changes in a source carborane pair, with explicit chemical differences between the pair.',
 'Use fused 2a C18H20B10 and nonfused source precursor1a C18H21B10Br, both neutral singlets. Precursor1a is 1-(8-bromonaphthalen-1-yl)-2-phenyl-o-carborane; it is not a pure geometric un-fusion because Br/H composition differs. Public graph edits remove the B3-aryl fusion edge, restore B3-H and add aryl-Br. Preserve the closo cage adjacency and mapped cage C1-C2 axis; a multicenter cage edge is not an ordinary two-center bond-order assertion. Primary THF continuum.',
 'The authors attribute optical changes to C-B arene fusion and report B3LYP/6-31G(d,p), IEF-PCM(THF), Gaussian09 TDDFT. SI separately reports fluoranthene/triphenylene controls, which are not unfused carboranes. The precursor and cage C-C displacement study here is a new bounded control; its Br confound must be retained in the interpretation.',
 'Main pp2-4 Schemes1-2 and optical discussion; SI pp4-5 identity1a, p19 methods/2a coordinates, pp10-15 optical context.',
 'Recheck full cage adjacency, frequency/state validity and the source precursor identity. Pilot a small symmetric cage C-C displacement and test electronic near-degeneracy.',
 [panel('fusion_pair',['fused2a','nonfused1a'],['excitation_eV','oscillator_strength','cage_CC_A','lowest_frequency_cm1'],'Require NTO/state character, valid ground-state modes and both distinct chemical identities; no KS-gap or NICS proxy for quantum yield.'),panel('cage_displacement',['2a_minus','2a_plus','1a_minus','1a_plus'],['displacement_A','relative_E_kJ_mol','excitation_eV','oscillator_strength'],'Use symmetric ±0.05 angstrom coordinate perturbations around each own relaxed C-C reference as design points, with fixed and orthogonally relaxed versions. The displacement size is a chosen intervention, not a reference tolerance.'),panel('causal_limits',['fusion_vs_motion','method_sensitivity'],['excitation_change_eV','response_eV_per_A','uncertainty_eV'],'Keep Br substitution as a chemical confound, report vibrational/displacement response and trigger higher-level diagnostics for near-degenerate state mixing. A compound conclusion need not isolate fusion uniquely.')],
 'Crystal emission requires real neighbors and independent convergence and is outside this core.')
add('a6e8c57709329bdb','HL metal association versus quenching selectivity',
 'Test whether preferential association and a metal-related dark/charge-transfer state are distinguishable explanations for HL response to Fe(III), using a source competing ion and balanced solution species.',
 'HL is the full C20H22N4O6 neutral singlet graph with two E imines and phenolic OH groups. Source sensing medium is DMF; Co(II) is selected because it is an explicitly measured partial-quenching competitor. Fe(III) spin space includes doublet/quartet/sextet; Co(II) doublet/quartet. Water/DMF ligands, protonation and counterions must be fixed with salt/pH data before a unique binding-energy cycle is defined. Do not compare unlike total compositions or assign selectivity from smallest gap.',
 'The authors use Gaussian09 B3LYP/6-31G(d,p) for free HL and propose Fe(III)-associated LMCT quenching; Fig4 also shows weaker response to Co/Mn/Pb. Mn-L is a separate heteroleptic binuclear complex involving HL-prime and is not a clean Fe-HL control. Expanded Fe/Co coordination/protonation and solution exchanges are new and not validated by free-ligand gap agreement.',
 'Main pp2,5-7 Fig4 and theoretical calculation section; SI FigsS5-S8/S20. DMF is explicit; salt counterion, water activity and pH for Fe/Co sensing are not established by the accessed records.',
 'Obtain the salt/counterion and acid/water boundary, define finite coordination/protonation with mass balance, then pilot a Fe/Co ligand-exchange pair and open-shell response.',
 [panel('coordination_candidates',['HL','Fe_HL_protonated','Fe_HL_deprotonated','Co_HL_protonated','Co_HL_deprotonated'],['G_Eh','spin_squared','excitation_eV','oscillator_strength'],'All models require atom-complete solvent/counterion/proton bookkeeping and applicable spin search; apparent nonconvergence is not proof a species is absent.'),panel('solution_cycles',['Fe_exchange','Co_exchange','proton_exchange'],['delta_G_kJ_mol','standard_state_correction_kJ_mol'],'Use one balanced exchange reference and explicit proton reservoir; bare Fe3+ binding in vacuum cannot be substituted for an unreported DMF experimental salt.'),panel('selectivity_tests',['binding_contrast','state_contrast','speciation_sensitivity'],['binding_difference_kJ_mol','excitation_difference_eV','CT_fraction_change'],'Keep binding preference separate from potential quenching channels, accept multiple Fe species consistent with evidence. TD/NTO alone does not produce a rate or detection limit.')],
 'Full quenching dynamics, detection limits and biological medium are optional.',
 'blocked_solution_definition: DMF and competing Co(II) are confirmed, but the accessed main/SI do not fix sensing salt counterions, pH/proton reservoir or water content. Define those from source records or an explicitly authorized model before atom-complete Fe/Co exchange references. No invented salt/pH or calibrated selectivity is supplied.')
add('b1467cd61ca8022d','LiFSI ether coordination and descriptor controls',
 'Test whether O/F chelation and anion competition support a molecular explanation of the solvent series beyond isolated-solvent descriptors.',
 'Use PM COCCC, BM COCCCC, TFPM COCCC(F)(F)F and TFBM COCCCC(F)(F)F; all solvent molecules neutral singlets. Li+ is singlet; FSI- is F-S(=O)2-N(-)-S(=O)2-F, singlet. Core clusters contain exactly one Li+, one FSI- and one solvent (total charge0 singlet). Compare O-facing, O/F-contact where F exists, and FSI-dominated orientations at identical composition. No 2 M bulk interpretation follows from this finite-cluster design.',
 'The authors use Gaussian16 B3LYP/6-311+G(d,p), define Eb=Ecomplex-E(Li+)-Esolvent, and use Multiwfn descriptors. Main/SI propose Li-O/F chelation and report MD separately. The eV RESPO axis is not an atomic RESP charge; electronic potential, fitted charges and dipole units must be distinguished. Neutral one-salt cluster competition and frozen/relaxed fragment controls are benchmark extensions.',
 'Main pp2-5,12 Fig2/methods; formal publisher SI pp5-8 FigsS5-S8 and p36 TableS1. Local supplementary_001 is a peer-review file, not the formal scientific SI.',
 'Confirm all four ether graphs and LiFSI charge; validate one O/F versus anion-contact pair with frequency/fragment energies, then calibrate analysis definitions.',
 [panel('cluster_orientations',[f'{x}_{y}' for x in ['PM','BM','TFPM','TFBM'] for y in ['solvent_contact','anion_contact']],['electronic_Eh','Li_O_A','Li_F_nearest_A','lowest_frequency_cm1'],'For nonfluorinated solvents any F contact is to FSI and must be labeled. Fluorinated candidates include attempted bidentate and O-only starts; retain real collapse evidence.'),panel('fragment_controls',['PM','BM','TFPM','TFBM'],['binding_kJ_mol','interaction_kJ_mol','distortion_kJ_mol','dipole_D','ESP_O_eV','RESP_O_e'],'Compute common-fragment interaction/distortion and state explicitly surface/isodensity/gauge for ESP. A gas-phase ion-solvent Eb and neutral salt-cluster interaction are separate quantities.'),panel('descriptor_test',['O_F_contrast','anion_competition','method_sensitivity'],['paired_energy_change_kJ_mol','uncertainty_kJ_mol'],'Test a descriptor prediction against actual coordination and anion intervention, not a restatement of source ordering. Do not infer conductivity/SEI or bulk RDF.')],
 '2 M molecular dynamics, RDF/CN, conductivity and battery performance are optional.')
add('c28b0a1c549f4575','Charge-balanced PC exchange and ion pairing',
 'Determine whether competitive PC association survives ion-pair geometry and finite solvation-number controls while maintaining complete charge and composition balance.',
 'DED is 1,4-diethyl-1,4-diazabicyclo[2.2.2]octane dication, not a neutral diamine. Define A=TEA+BF4- and B=DED2+(BF4-)2 (both charge0 singlet). For each use one and two PC molecules in contact and separated configurations. PC is racemic; choose a fixed stereochemical composition and report it. Compare PC transfer A.PC+B -> A+B.PC and the corresponding second-PC exchange; compare contact/separated at equal solvent count. Source 1 M TEABF4 +0.2 M DED salt is experimental context, not a finite-cluster concentration.',
 'The source suggests DED2+ competes for PC and facilitates TEA desolvation. Gaussian16 B3LYP-D3BJ/def2-SVP optimization/frequency and B3LYP/6-311+G(2d,p) binding single points are reported; frontier orbital protocol differs. Explicit neutral ion-pair and solvent-count exchange controls below are benchmark extensions; they cannot establish capacitance or cycling life.',
 'Main pp1-3 electrolyte identity and association; SI pp5-6 computational details.',
 'Verify DED ethylated quaternary-N graph and two BF4 anions. Pilot contact/separated A.PC and one balanced PC exchange with DFT refinement.',
 [panel('equal_composition_clusters',[f'{ion}_PC{n}_{contact}' for ion in ['TEA','DED'] for n in [1,2] for contact in ['contact','separated']],['electronic_Eh','G_Eh','ion_pair_distance_A'],'Keep correct anion count and PC count; separated structures may collapse, but only actual mapped optimization evidence establishes that fact.'),panel('PC_exchange',['first_PC','second_PC'],['electronic_exchange_kJ_mol','free_energy_exchange_kJ_mol','distortion_kJ_mol'],'Balance both salt compositions and every PC molecule. Record component energies and coefficients so the exchange is recomputable; no direct ranking of charged DED-PC versus TEA-PC totals.'),panel('ion_pair_control',['TEA_contact_effect','DED_contact_effect','conformer_sensitivity'],['delta_E_kJ_mol','delta_G_kJ_mol','uncertainty_kJ_mol'],'Separate ion pairing, PC coordination count and conformer uncertainty; conclusions only concern finite molecular necessary conditions.')],
 'Capacity, cycling lifetime and bulk GROMACS are optional.')
add('2877efc02814175d','DQCS metal versus ligand-geometry excitation effects',
 'Discriminate metal-induced electronic changes from ligand deformation in Cd/Co/Ni DQCS complexes, using free and frozen ligand controls and properly treated open-shell response.',
 'Full neutral DQCS is C31H27N3O3 singlet; retain the phenolic hydrogen present in the three source graphs. Metal complexes all have charge+2; Cd/Co/Ni source multiplicities are1/2/1. Primary medium DMSO. A free ligand extracted from a complex has charge0 singlet, not the parent complex charge. Identify ligand versus metal density partitions and fixed-geometry atom correspondence.',
 'The authors use Gaussian09 B3LYP/6-311G(d,p) for DQCS and B3LYP/LanL2DZ for complexes in DMSO. SI S2 explicitly makes Co a doublet, although S8 labels its table as singlet transitions; that table heading must not force closed-shell Co TD. Gap, hardness and electrophilicity are algebraically related, not three independent mechanisms. Frozen-ligand controls are new.',
 'Recovered user-supplied main PDF (10 pages; source_data/user_supplied_20260925/1-s2.0-S0022286025023567-main.pdf), p2 computational section and pp7-8 Figs8-10; SI pp11-13 TablesS1-S3 and p18 TableS8 directly checked. The default papers/main.pdf has no readable body and is not the evidence source. Experimental sensing is DMSO/water9:1, distinct from the bounded DMSO electronic calculation.',
 'Remove the metal from a verified 65-atom complex and check full neutral 64-atom ligand electron count; validate Co unrestricted response and spin before comparing NTO partitions.',
 [panel('relaxed_species',['DQCS','Cd_DQCS','Co_DQCS','Ni_DQCS'],['excitation_eV','oscillator_strength','metal_transition_fraction','spin_squared'],'Compute like-defined TD/NTO observables with six roots or a justified larger window. Co transitions retain doublet reference/spin character rather than forced singlet labels.'),panel('frozen_ligand',['ligand_from_Cd','ligand_from_Co','ligand_from_Ni'],['excitation_eV','oscillator_strength','ligand_distortion_kJ_mol'],'Extract identical complete ligand graph/charge from each source complex, retaining all hydrogens; pair frozen and relaxed ligand results.'),panel('attribution',['Cd_effect','Co_effect','Ni_effect','method_sensitivity'],['electronic_shift_eV','geometry_shift_eV','uncertainty_eV'],'Separate geometry and metal contributions with state matching and real density fractions. Do not use gap/hardness/electrophilicity algebra as independent causal evidence.')],
 'DNA association, quenching rates and antibacterial mechanism are optional.')
add('2f2aa11ea61a32bb','Boron monomer spectra under common geometry controls',
 'Explain spectral differences across source monomers1a-1d by testing electronic substitution/topology effects against common local geometry and matched transition character.',
 'Use neutral singlet 1a C11H8BF2NO and 1b/1c/1d C15H10BF2NO; retain their distinct azaarene fusion/connectivity. Primary toluene medium matches experimental_absorption.json and main Fig2/Table1. A gas-phase source baseline is a separate sensitivity, not a toluene measurement. A shared geometry means a mapped local B-N-O/chelate scaffold, not a forced whole-graph atom bijection across different fused isomers. Geometry constraints must be stated and released controls retained.',
 'The authors use Gaussian16 B3LYP/6-31+G(d,p), frequency validation and TDDFT to assign low-energy bands, including dark versus bright transitions. Public experimental absorption is input evidence. Common-chelate interventions and an independently retained spectral trend are benchmark additions. The paper crystallographic white-light/polymorph results are outside this molecular first version.',
 'Main pp2-3 Fig2/Table1 explicitly identifies toluene absorption; SI p2 methods, pp57-68 coordinate tables. Current experimental_absorption.json is retained as published input.',
 'Audit four graphs, map the common chelate and state identities, then pilot one common-geometry comparison before full series intervention.',
 [panel('relaxed_monomers',['1a','1b','1c','1d'],['excitation_eV','oscillator_strength','CT_distance_A'],'Retain low-root tables, full oscillator distribution and NTOs; observed absorption maximum need not be S1 when a dark state is lower.'),panel('common_geometry',['1a_common','1b_common','1c_common','1d_common'],['excitation_eV','oscillator_strength','constraint_deformation_kJ_mol'],'Actual shared-chelate constraints with atom correspondence and released pairs are mandatory; four original spectra alone are insufficient.'),panel('spectral_test',['electronic_vs_geometry','independent_trend','method_sensitivity'],['predicted_shift_eV','observed_shift_eV','uncertainty_eV'],'Separate band energy, intensity and character, with stated broadening/assignment and digitization uncertainty. A retrospective holdout must not be mislabeled a blind prediction.')],
 'Real crystal dimers, polymorph mapping and white-light mechanisms are separate optional modules.')
add('3a22e838133b906d','Phosphonate-borane dealkylation and Li aggregation',
 'Separate local dealkylation, Li coordination, MeCN coordination and real dimerization contributions to P-O...B geometry through atom-balanced hierarchical models.',
 'Use full source BCy2/o-phenyl phosphonate 2a and deethylated anion3, not only BMe2/OMe surrogate. Full anion is C20H31BO3P, charge-1 singlet; Li+ and MeCN are singlets. Source Li2O2 dimer has two anions, two Li and four MeCN (charge0 singlet). Each Li coordinates the exposed phosphoryl O of both anions and two MeCN N atoms; intramolecular O->B contact remains distinguishable. Use balanced 2 monomer -> dimer and MeCN association cycles. Dealkylation reaction is neutral+LiI -> Li.anion+EtI; do not subtract unlike neutral/anion total energies.',
 'Main Fig1 shows an inversion-related Li2O2-bridged dimer with two MeCN ligands on each Li. Authors use Gaussian16 B3LYP-D3(BJ)/6-311++G(2d,p) on small neutral/anion models and explicitly acknowledge omitted Li coordination. Full molecular, solvent-coordination and dimer contrasts are new and require direct calculation; small-model agreement cannot certify the aggregate.',
 'Main pp1-3 Scheme1/Fig1, including Li2O2 paragraph p2; SI pp62,69 crystal data and p78 computation; old public model graphs are retained only as labeled truncation controls.',
 'Validate full anion and neutral Li(MeCN)2 monomer, then pilot the minimum 2-anion/2-Li/4-MeCN dimer and its dissociation counterpart. Atom inventory/coordination follows Fig1; no fabricated crystal coordinates are supplied.',
 [panel('coordination_layers',['full_anion','Li_anion','Li_anion_2MeCN','crystal_supported_dimer'],['P_O_A','B_O_A','electronic_Eh','G_Eh'],'Maintain full Cy and OEt groups and distinguish dimer versus monomer identities; every geometry needs genuine convergence and frequency/constraint evidence.'),panel('balanced_cycles',['Li_association','MeCN_association','dimerization','deethylation'],['delta_E_kJ_mol','delta_G_kJ_mol','distortion_kJ_mol'],'Recompute fragment/stoichiometry-balanced differences; explicit LiI/EtI or equivalent balanced deethylation accounting is required, never bare neutral-minus-anion energy.'),panel('truncation_and_mechanism',['small_vs_full','coordination_vs_aggregation'],['P_O_change_A','B_O_change_A','interaction_change_kJ_mol'],'A full dimer is required for aggregation credit and paired small/full models for truncation. Local isolated-anion results do not explain the whole salt; no electrolyte performance claims.')],
 'A smaller local-only version would need separate scope deletion of aggregation; the present first version retains a mandatory full dimer.')
add('98b6f8a0352f72c2','Phenazine substituent and solvent excited-state controls',
 'Determine whether donor substitution and solvent effects on absorption, emission and CT survive matched torsional geometry and consistent state definitions.',
 'Select real members12a (NMe2, C24H19N3) and12d (NEt2, C26H23N3), neutral singlets, in CHCl3 and EtOAc. Each requires S0 preparation, vertical TD at S0, tracked relaxed S1 and vertical emission at S1; report the adiabatic energy separately. Use the mapped phenyl-phenazine single-bond torsion as common intervention. Calculate experimental kr=Phi/tau only if both measured values refer to the same conditions; 1/tau alone is total decay, not radiative rate.',
 'The authors use ORCA4.2 omegaB97X-D3/def2-TZVP/def2-J, CPCM CHCl3 and40 singlet roots, with NTOs and oscillator-strength-derived lifetimes. Formal SI FiguresS31-S39 and TableS1 include EtOAc and CHCl3 calculations. Theoretical radiative lifetime is not a measured fluorescence lifetime; source main/old reference lifetime discrepancy must be disclosed. Relaxed S1, paired torsion and two-solvent tests are new.',
 'Main pp3-5 optical tables/Figs and pp7-8 section3.1.4; formal publisher DOCX FigsS31-S39/TableS1 (downloaded and read in batch evidence), member12d synthesis/identity main pp6-7.',
 'Verify 12a/12d graphs and two media, then pilot one tracked S1 in both solvents with cross-program/state mapping. No series regression before states are matched.',
 [panel('solvent_series',[f'{m}_{s}' for m in ['12a','12d'] for s in ['CHCl3','EtOAc']],['absorption_eV','emission_eV','adiabatic_eV','oscillator_strength','transition_dipole_D','CT_distance_A'],'Save S0/S1 outputs, geometry and NTO evidence with solvent response convention; never equate absorption oscillator strength with measured radiative yield.'),panel('common_torsion',[f'{m}_{s}' for m in ['12a','12d'] for s in ['CHCl3','EtOAc']],['torsion_degree','absorption_eV','emission_eV','oscillator_strength'],'Freeze identical mapped phenyl-phenazine angle, compare released structures and track state; distinguish ground/excited geometry relaxation.'),panel('rates_and_robustness',['radiative_convention','substitution_vs_solvent','state_sensitivity'],['theoretical_radiative_rate_s1','rate_uncertainty_s1','excitation_change_eV'],'State refractive-index/local-field/degeneracy convention and formula, and whether an experimental Phi/tau comparison is available. Do not invent missing quantum yields or treat SI theoretical lifetimes as measurements.')],
 'Thin-film nonradiative lifetimes and full device efficiency are optional.')

# Supervisor object-specific metric applicability, 2026-09-27
_metric_applicability_rules = {'paper_b276b18215cba283': {'panel': 'arm_geometry_control', 'rows': {'single_on_three_transoid': ['interarm_transfer_fraction'], 'single_on_three_cisoid': ['interarm_transfer_fraction']}, 'note': 'For single_on_three_transoid and single_on_three_cisoid, interarm_transfer_fraction is null with metric_applicability_reason: the capped single-arm object has no second arm. Excitation, oscillator strength and the mapped frozen-arm calculation remain mandatory. The three_fixed_arm row still requires a numeric interarm transfer fraction from the full three-arm transition density, with explicit fragment partitions and normalization; null is forbidden there.'}, 'paper_a0f6b899582cb9f7': {'panel': 'truncation_and_tensor', 'rows': {'M3_tensor': ['primary_interaction_kJ_mol', 'control_interaction_kJ_mol']}, 'note': 'For the isolated M3_tensor row, primary_interaction_kJ_mol and control_interaction_kJ_mol are null with metric_applicability_reason because no partner is present. The full quadrupole tensor, declared origin/axes and numeric quadrupole_zz_eA2 remain mandatory. The larger_fragment row still requires both real interaction energies, a mapped larger-fragment pair and the shared M3 tensor; null cannot waive that truncation comparison. The capped-fragment input gate remains blocked.'}}
for _pid, _rule in _metric_applicability_rules.items():
 for _panel in S[_pid]["panels"]:
  if _panel["name"] != _rule["panel"]: continue
  _panel["criterion"] += " " + _rule["note"]
  _panel["metric_overrides"] = {}
  for _row, _fields in _rule["rows"].items():
   _panel["metric_overrides"][_row] = {_f: {"const": None, "description": _rule["note"]} for _f in _fields}
   _panel["metric_overrides"][_row]["metric_applicability_reason"] = {"type": "string", "minLength": 1, "description": _rule["note"]}
