"""Static, task-independent ActionSpec and BackendSpec declarations."""

from __future__ import annotations

from .models import ActionSpec, BackendSpec


def _action(
    action_id: str,
    category: str,
    description: str,
    primary_output: str,
    backends: tuple[str, ...],
    required: tuple[str, ...],
    optional: tuple[str, ...] = (),
    *,
    input_description: str = "",
    data_action: bool = False,
    requires_network: bool = False,
) -> ActionSpec:
    return ActionSpec(
        id=action_id,
        category=category,
        description=description,
        primary_output=primary_output,
        backend_ids=backends,
        required_inputs=required,
        optional_inputs=optional,
        input_description=input_description,
        data_action=data_action,
        requires_network=requires_network,
    )


ACTION_SPECS: tuple[ActionSpec, ...] = (
    _action(
        "standardize_structure",
        "structure_and_system",
        "Standardize one molecular representation without generating 3D coordinates or optimizing geometry.",
        "AtomicStructure",
        ("rdkit",),
        ("structure",),
        input_description="structure: SMILES or a molecule/structure object",
    ),
    _action(
        "generate_3d_structure",
        "structure_and_system",
        "Generate one explicit three-dimensional structure from a two-dimensional molecular representation.",
        "AtomicStructure",
        ("rdkit", "openbabel"),
        ("molecule",),
        input_description="molecule: standardized SMILES or molecule object",
    ),
    _action(
        "generate_conformer_ensemble",
        "structure_and_system",
        "Generate a conformer ensemble; it does not perform the later quantum refinement or final ranking workflow.",
        "ConformerEnsemble",
        ("rdkit_etkdg", "crest"),
        ("molecule",),
        ("initial_structure",),
        input_description="molecule plus optional initial_structure Artifact for CREST",
    ),
    _action(
        "rank_conformers_from_results",
        "structure_and_system",
        "Rank and weight conformers only from aligned energies or free energies already supplied by the agent.",
        "ConformerEnsemble",
        ("internal_statistics",),
        ("ensemble", "scores"),
        input_description="ensemble and one aligned score record per conformer",
    ),
    _action(
        "repair_biomolecular_structure",
        "structure_and_system",
        "Repair missing biomolecular residues or atoms without choosing protonation, force field, solvent, or dynamics settings.",
        "AtomicStructure",
        ("pdbfixer",),
        ("structure",),
        input_description="biomolecular structure or workspace PDB Artifact",
    ),
    _action(
        "assign_protonation_states",
        "structure_and_system",
        "Assign explicit protonation states using the agent-selected backend and pH/rule settings.",
        "AtomicStructure",
        ("rdkit", "pdbfixer"),
        ("structure",),
        input_description="standardized or repaired structure",
    ),
    _action(
        "assign_partial_charges",
        "structure_and_system",
        "Assign named force-field or docking partial charges without parameterizing or solvating the system.",
        "ChargedStructure",
        ("rdkit_gasteiger", "openff_am1bcc"),
        ("structure",),
        input_description="structure with the desired protonation state already fixed",
    ),
    _action(
        "assign_force_field_parameters",
        "structure_and_system",
        "Assign an explicitly selected force field to an already prepared molecular system.",
        "ParameterizedSystem",
        ("openff", "openmm_builder"),
        ("structure",),
        ("charges",),
        input_description="prepared structure plus optional ChargedStructure Artifact",
    ),
    _action(
        "solvate_molecular_system",
        "structure_and_system",
        "Build the explicitly requested solvent/ion environment without minimizing or propagating dynamics.",
        "ParameterizedSystem",
        ("openmm_builder", "packmol"),
        ("system",),
        input_description="ParameterizedSystem plus explicit box, solvent, and ion settings",
    ),
    _action(
        "calculate_energy",
        "molecular_electronic",
        "Calculate one molecular or non-periodic scalar energy with the exact software and method selected by the agent.",
        "EnergyResult",
        ("xtb", "pyscf", "psi4", "tblite", "mace", "chgnet", "orca", "ase_emt"),
        ("structure",),
        input_description="non-periodic AtomicStructure",
    ),
    _action(
        "calculate_forces",
        "molecular_electronic",
        "Calculate atomic forces for one non-periodic structure or an aligned batch.",
        "ForceResult",
        ("tblite", "mace", "chgnet", "ase_emt"),
        ("structure",),
        input_description="AtomicStructure or a homogeneous structure batch",
    ),
    _action(
        "calculate_hessian",
        "molecular_electronic",
        "Calculate one molecular Hessian without deriving modes, spectra, or thermochemistry.",
        "Hessian",
        ("xtb", "psi4", "tblite", "orca", "ase_emt"),
        ("structure",),
        input_description="AtomicStructure",
    ),
    _action(
        "optimize_geometry",
        "molecular_electronic",
        "Optimize one non-periodic geometry and return the optimized structure only as the primary result.",
        "AtomicStructure",
        ("xtb", "tblite", "mace", "chgnet", "orca", "ase_emt"),
        ("structure",),
        input_description="AtomicStructure plus explicit convergence and optional constraints",
    ),
    _action(
        "calculate_dipole_moment",
        "molecular_electronic",
        "Calculate one molecular dipole moment with an explicitly chosen electronic method.",
        "DipoleResult",
        ("tblite", "pyscf", "psi4", "orca"),
        ("structure",),
        input_description="AtomicStructure",
    ),
    _action(
        "calculate_atomic_charges",
        "molecular_electronic",
        "Calculate electronic-structure population-analysis charges without attaching force-field parameters.",
        "AtomicChargeResult",
        ("pyscf", "psi4"),
        ("structure",),
        input_description="AtomicStructure or compatible ElectronicState Artifact",
    ),
    _action(
        "calculate_orbitals",
        "molecular_electronic",
        "Calculate orbital energies, occupations, and optional coefficient artifacts.",
        "OrbitalResult",
        ("pyscf", "psi4"),
        ("structure",),
        input_description="AtomicStructure or compatible ElectronicState Artifact",
    ),
    _action(
        "derive_vibrational_modes",
        "molecular_electronic",
        "Derive frequencies and normal modes from an existing Hessian and structure.",
        "FrequencyResult",
        ("internal_vibrations",),
        ("hessian", "structure"),
        input_description="Hessian Artifact and matching AtomicStructure",
    ),
    _action(
        "derive_ir_spectrum",
        "molecular_electronic",
        "Construct an IR spectrum from vibration results that already contain intensities.",
        "SpectrumResult",
        ("internal_spectroscopy",),
        ("vibrations",),
        input_description="FrequencyResult with intensities",
    ),
    _action(
        "derive_thermochemistry",
        "molecular_electronic",
        "Derive thermochemical quantities from supplied electronic energy and frequencies; no optimization or Hessian is hidden.",
        "ThermochemistryResult",
        ("internal_thermochemistry", "goodvibes"),
        ("energy", "frequencies"),
        input_description="EnergyResult and FrequencyResult or a compatible parsed output Artifact",
    ),
    _action(
        "locate_transition_state",
        "reaction_and_kinetics",
        "Locate one candidate transition-state structure without automatically running frequencies or IRC.",
        "AtomicStructure",
        ("pysisyphus",),
        ("initial_guess",),
        ("reactant", "product"),
        input_description="candidate structure and optional endpoint structures",
    ),
    _action(
        "trace_intrinsic_reaction_coordinate",
        "reaction_and_kinetics",
        "Trace an IRC from an already supplied transition-state structure.",
        "ReactionPath",
        ("pysisyphus",),
        ("transition_state",),
        input_description="validated candidate transition-state structure",
    ),
    _action(
        "calculate_chemical_equilibrium",
        "reaction_and_kinetics",
        "Calculate an equilibrium composition/state for an explicitly supplied mechanism and thermodynamic condition.",
        "EquilibriumResult",
        ("cantera",),
        ("composition",),
        ("mechanism",),
        input_description="composition and optional mechanism Artifact",
    ),
    _action(
        "integrate_reaction_network",
        "reaction_and_kinetics",
        "Integrate one explicitly specified reaction network over time.",
        "KineticsTrajectory",
        ("scipy", "cantera"),
        ("network", "initial_state"),
        input_description="ReactionNetwork and initial concentrations/state",
    ),
    _action(
        "solve_microkinetic_model",
        "reaction_and_kinetics",
        "Solve one explicitly supplied microkinetic model without constructing the reaction model for the agent.",
        "MicrokineticResult",
        ("catmap",),
        ("model",),
        input_description="typed microkinetic model object",
    ),
    _action(
        "minimize_system_energy",
        "molecular_dynamics",
        "Minimize an already parameterized system without automatically equilibrating or propagating dynamics.",
        "ParameterizedSystem",
        ("openmm", "gromacs", "lammps"),
        ("system",),
        input_description="ParameterizedSystem Artifact",
    ),
    _action(
        "propagate_dynamics",
        "molecular_dynamics",
        "Propagate exactly one agent-defined dynamics segment and return its trajectory and final state.",
        "Trajectory",
        ("openmm", "gromacs", "lammps"),
        ("system",),
        input_description="ParameterizedSystem or previous final-state Artifact",
    ),
    _action(
        "calculate_trajectory_rmsd",
        "molecular_dynamics",
        "Calculate an RMSD time series for an explicitly selected trajectory atom group and reference.",
        "TimeSeries",
        ("mdanalysis",),
        ("trajectory", "topology"),
        ("reference",),
        input_description="trajectory/topology Artifacts and optional reference",
    ),
    _action(
        "calculate_radius_of_gyration",
        "molecular_dynamics",
        "Calculate the radius-of-gyration time series for an explicitly selected atom group.",
        "TimeSeries",
        ("mdanalysis",),
        ("trajectory", "topology"),
        input_description="trajectory/topology Artifacts",
    ),
    _action(
        "calculate_radial_distribution",
        "molecular_dynamics",
        "Calculate one radial distribution function for two explicitly selected atom groups.",
        "DistributionResult",
        ("mdanalysis",),
        ("trajectory", "topology"),
        input_description="trajectory/topology Artifacts",
    ),
    _action(
        "calculate_mean_squared_displacement",
        "molecular_dynamics",
        "Calculate one mean-squared-displacement time series for an explicitly selected atom group.",
        "TimeSeries",
        ("mdanalysis",),
        ("trajectory", "topology"),
        input_description="trajectory/topology Artifacts",
    ),
    _action(
        "evaluate_collective_variables",
        "molecular_dynamics",
        "Evaluate explicitly defined collective variables on an existing trajectory.",
        "TimeSeries",
        ("plumed",),
        ("trajectory", "topology", "collective_variables"),
        input_description="trajectory/topology plus typed collective-variable definitions",
    ),
    _action(
        "calculate_periodic_energy",
        "periodic_and_phonons",
        "Calculate one periodic-system energy with the explicitly selected electronic-structure backend.",
        "EnergyResult",
        ("quantum_espresso", "cp2k", "siesta", "dftbplus", "abinit"),
        ("structure",),
        input_description="periodic AtomicStructure with cell and PBC",
    ),
    _action(
        "calculate_periodic_forces",
        "periodic_and_phonons",
        "Calculate periodic atomic forces for one structure or aligned displaced-structure batch.",
        "ForceResult",
        ("quantum_espresso", "cp2k", "siesta", "dftbplus", "abinit"),
        ("structure",),
        input_description="periodic AtomicStructure or homogeneous structure batch",
    ),
    _action(
        "calculate_periodic_stress",
        "periodic_and_phonons",
        "Calculate one periodic stress tensor without relaxing the structure.",
        "StressResult",
        ("quantum_espresso", "cp2k", "abinit"),
        ("structure",),
        input_description="periodic AtomicStructure",
    ),
    _action(
        "relax_periodic_structure",
        "periodic_and_phonons",
        "Relax a periodic structure under explicit atomic/cell constraints.",
        "AtomicStructure",
        ("quantum_espresso", "cp2k", "siesta", "dftbplus", "abinit"),
        ("structure",),
        input_description="periodic AtomicStructure plus explicit relaxation controls",
    ),
    _action(
        "generate_displaced_supercells",
        "periodic_and_phonons",
        "Generate a displacement set from an explicit supercell matrix and displacement amplitude.",
        "DisplacementSet",
        ("phonopy", "phono3py"),
        ("structure",),
        input_description="periodic AtomicStructure",
    ),
    _action(
        "assemble_force_constants",
        "periodic_and_phonons",
        "Assemble force constants only from a supplied displacement set and aligned forces.",
        "ForceConstants",
        ("phonopy", "phono3py"),
        ("displacement_set", "force_set"),
        input_description="DisplacementSet and ForceSet Artifacts",
    ),
    _action(
        "calculate_phonon_dispersion",
        "periodic_and_phonons",
        "Calculate a phonon dispersion from existing force constants and an explicit q-point path.",
        "PhononDispersion",
        ("phonopy", "phono3py"),
        ("force_constants", "structure"),
        input_description="ForceConstants, structure, and q_path setting",
    ),
    _action(
        "calculate_phonon_density_of_states",
        "periodic_and_phonons",
        "Calculate a phonon density of states from existing force constants and an explicit q mesh.",
        "PhononDensityOfStates",
        ("phonopy", "phono3py"),
        ("force_constants", "structure"),
        input_description="ForceConstants, structure, and q_mesh setting",
    ),
    _action(
        "dock_ligand",
        "docking",
        "Dock an already prepared ligand into an already prepared receptor using an explicit search space.",
        "DockingResult",
        ("vina", "gnina"),
        ("receptor", "ligand", "search_space"),
        ("charges",),
        input_description="prepared receptor/ligand Artifacts and explicit box center/size",
    ),
    _action(
        "search_compounds",
        "data_sources",
        "Search PubChem compound records by an explicit identifier and namespace.",
        "CompoundRecords",
        ("pubchem",),
        ("query",),
        input_description="query string plus namespace/max_records settings",
        data_action=True,
        requires_network=True,
    ),
    _action(
        "search_protein_structures",
        "data_sources",
        "Search or retrieve RCSB PDB structure records using explicit identifiers or query terms.",
        "ProteinStructureRecords",
        ("rcsb_pdb",),
        ("query",),
        input_description="PDB id or search query",
        data_action=True,
        requires_network=True,
    ),
    _action(
        "search_materials",
        "data_sources",
        "Search Materials Project records by material id, formula, or explicit query fields.",
        "MaterialRecords",
        ("materials_project",),
        ("query",),
        input_description="material id, formula, or structured query",
        data_action=True,
        requires_network=True,
    ),
    _action(
        "search_catalysis_records",
        "data_sources",
        "Search Catalysis-Hub reaction records using explicit reactant/product filters.",
        "CatalysisRecords",
        ("catalysis_hub",),
        ("query",),
        input_description="structured reactant/product query",
        data_action=True,
        requires_network=True,
    ),
)


def _backend(
    backend_id: str,
    display_name: str,
    runtime: str,
    capabilities: tuple[str, ...],
    description: str,
    *,
    modules: tuple[str, ...] = (),
    executables: tuple[str, ...] = (),
    environment: tuple[str, ...] = (),
    conda: tuple[str, ...] = (),
    pip: tuple[str, ...] = (),
    data_resources: tuple[str, ...] = (),
    license_class: str = "open_source",
    install_notes: str = "",
    method_schema: dict[str, str] | None = None,
    required_methods: dict[str, tuple[str, ...]] | None = None,
    required_settings: dict[str, tuple[str, ...]] | None = None,
) -> BackendSpec:
    return BackendSpec(
        id=backend_id,
        display_name=display_name,
        runtime=runtime,
        capabilities=capabilities,
        description=description,
        python_modules=modules,
        executables=executables,
        environment_variables=environment,
        conda_packages=conda,
        pip_packages=pip,
        required_data_resources=data_resources,
        license_class=license_class,
        install_notes=install_notes,
        method_schema=method_schema or {},
        required_method_fields=required_methods or {},
        required_setting_fields=required_settings or {},
    )


_PERIODIC_RELAX = {
    "relax_periodic_structure": (
        "force_threshold_ev_per_angstrom",
        "max_steps",
        "relax_cell",
    )
}


_DFTB_SETTINGS = {
    "calculate_periodic_energy": ("scc_tolerance", "max_scc_iterations"),
    "calculate_periodic_forces": ("scc_tolerance", "max_scc_iterations"),
    "relax_periodic_structure": (
        "scc_tolerance",
        "max_scc_iterations",
        "force_threshold_ev_per_angstrom",
        "max_steps",
        "relax_cell",
    ),
}


BACKEND_SPECS: tuple[BackendSpec, ...] = (
    _backend(
        "rdkit", "RDKit", "core",
        ("standardize_structure", "generate_3d_structure", "assign_protonation_states"),
        "Cheminformatics structure standardization, hydrogen handling, and 3D embedding.",
        modules=("rdkit",), conda=("rdkit",),
        required_settings={
            "standardize_structure": ("largest_fragment", "neutralize", "canonical_tautomer"),
            "generate_3d_structure": ("random_seed",),
            "assign_protonation_states": ("ph", "rule"),
        },
    ),
    _backend(
        "openbabel", "Open Babel", "quantum", ("generate_3d_structure",),
        "Open Babel 3D coordinate generation.", modules=("openbabel",), executables=("obabel",),
        conda=("openbabel",),
        required_methods={"generate_3d_structure": ("force_field",)},
    ),
    _backend(
        "rdkit_etkdg", "RDKit ETKDG", "core", ("generate_conformer_ensemble",),
        "RDKit ETKDG conformer generation with agent-selected sampling settings.",
        modules=("rdkit",), conda=("rdkit",),
        required_settings={"generate_conformer_ensemble": ("num_conformers", "random_seed")},
    ),
    _backend(
        "crest", "CREST", "reaction", ("generate_conformer_ensemble",),
        "CREST conformer search from an explicit starting geometry.", executables=("crest",),
        environment=("CHEMGRAPH_CREST_COMMAND",), conda=("crest", "xtb"),
        required_methods={"generate_conformer_ensemble": ("method",)},
    ),
    _backend(
        "internal_statistics", "ResearchChem deterministic statistics", "core",
        ("rank_conformers_from_results",),
        "Deterministic sorting, degeneracy handling, and Boltzmann weighting of supplied scores.",
        required_settings={"rank_conformers_from_results": ("temperature_kelvin", "score_unit")},
    ),
    _backend(
        "pdbfixer", "PDBFixer", "md",
        ("repair_biomolecular_structure", "assign_protonation_states"),
        "Biomolecular structure repair and explicit pH-based hydrogen addition.",
        modules=("pdbfixer", "openmm"), conda=("pdbfixer", "openmm"),
        required_settings={
            "repair_biomolecular_structure": ("add_missing_residues", "replace_nonstandard_residues", "keep_water"),
            "assign_protonation_states": ("ph",),
        },
    ),
    _backend(
        "rdkit_gasteiger", "RDKit Gasteiger charges", "core", ("assign_partial_charges",),
        "Gasteiger partial-charge assignment on a fixed molecular graph.", modules=("rdkit",),
        conda=("rdkit",), required_methods={"assign_partial_charges": ("charge_model",)},
    ),
    _backend(
        "openff_am1bcc", "OpenFF AM1-BCC", "openff", ("assign_partial_charges",),
        "OpenFF AM1-BCC partial-charge assignment through the AmberTools toolkit wrapper.",
        modules=("openff.toolkit",), executables=("antechamber", "sqm"),
        conda=("openff-toolkit", "ambertools"),
        required_methods={"assign_partial_charges": ("charge_model",)},
    ),
    _backend(
        "openff", "OpenFF Toolkit/Interchange", "openff", ("assign_force_field_parameters",),
        "OpenFF force-field parameter assignment and interchange serialization.",
        modules=("openff.toolkit", "openff.interchange"),
        conda=("openff-toolkit", "openff-interchange"),
        required_methods={"assign_force_field_parameters": ("force_field",)},
    ),
    _backend(
        "openmm_builder", "OpenMM system builder", "md",
        ("assign_force_field_parameters", "solvate_molecular_system"),
        "OpenMM force-field assignment and explicit solvent/ion construction.",
        modules=("openmm",), conda=("openmm",),
        required_methods={"assign_force_field_parameters": ("force_field",)},
        required_settings={
            "solvate_molecular_system": ("box_shape", "padding_angstrom", "solvent_model"),
        },
    ),
    _backend(
        "packmol", "Packmol", "md", ("solvate_molecular_system",),
        "Packmol construction of an explicitly specified molecular environment.",
        executables=("packmol",), conda=("packmol",),
        required_settings={
            "solvate_molecular_system": (
                "box_shape",
                "box_size_angstrom",
                "solvent_model",
                "solvent_path",
                "molecule_counts",
            ),
        },
    ),
    _backend(
        "xtb", "xTB", "quantum",
        ("calculate_energy", "calculate_hessian", "optimize_geometry"),
        "Standalone xTB GFN calculations.", executables=("xtb",),
        environment=("CHEMGRAPH_XTB_COMMAND",), conda=("xtb",),
        required_methods={
            "calculate_energy": ("method",), "calculate_hessian": ("method",),
            "optimize_geometry": ("method",),
        }, required_settings={"optimize_geometry": ("optimization_level",)},
    ),
    _backend(
        "pyscf", "PySCF", "quantum",
        ("calculate_energy", "calculate_dipole_moment", "calculate_atomic_charges", "calculate_orbitals"),
        "PySCF molecular Hartree-Fock and density-functional calculations.", modules=("pyscf",),
        pip=("pyscf",), method_schema={"method": "rhf|uhf|rks|uks", "basis": "PySCF basis name"},
        required_methods={
            action: ("method", "basis") for action in
            ("calculate_energy", "calculate_dipole_moment", "calculate_atomic_charges", "calculate_orbitals")
        },
    ),
    _backend(
        "psi4", "Psi4", "psi4",
        ("calculate_energy", "calculate_hessian", "calculate_dipole_moment", "calculate_atomic_charges", "calculate_orbitals"),
        "Psi4 molecular electronic-structure calculations.", modules=("psi4",), executables=("psi4",),
        conda=("psi4",), required_methods={
            action: ("method", "basis") for action in
            ("calculate_energy", "calculate_hessian", "calculate_dipole_moment", "calculate_atomic_charges", "calculate_orbitals")
        },
    ),
    _backend(
        "tblite", "TBLite", "quantum",
        ("calculate_energy", "calculate_forces", "calculate_hessian", "optimize_geometry", "calculate_dipole_moment"),
        "TBLite GFN calculator through its Python/ASE interface.", modules=("tblite", "ase"),
        pip=("tblite==0.4.0",), required_methods={
            action: ("method",) for action in
            ("calculate_energy", "calculate_forces", "calculate_hessian", "optimize_geometry", "calculate_dipole_moment")
        }, required_settings={
            "calculate_hessian": ("displacement_angstrom",),
            "optimize_geometry": ("fmax_ev_per_angstrom", "optimizer", "max_steps"),
        },
    ),
    _backend(
        "mace", "MACE", "mlip", ("calculate_energy", "calculate_forces", "optimize_geometry"),
        "MACE machine-learned interatomic potential with explicit model/device selection.",
        modules=("mace.calculators", "ase"), pip=("mace-torch==0.3.16",),
        required_methods={action: ("model", "device", "allow_model_download") for action in ("calculate_energy", "calculate_forces", "optimize_geometry")},
        required_settings={"optimize_geometry": ("fmax_ev_per_angstrom", "optimizer", "max_steps")},
    ),
    _backend(
        "chgnet", "CHGNet", "mlip", ("calculate_energy", "calculate_forces", "optimize_geometry"),
        "CHGNet machine-learned interatomic potential with explicit model/device selection.",
        modules=("chgnet", "ase"), pip=("chgnet",),
        required_methods={action: ("model", "device", "allow_model_download") for action in ("calculate_energy", "calculate_forces", "optimize_geometry")},
        required_settings={"optimize_geometry": ("fmax_ev_per_angstrom", "optimizer", "max_steps")},
    ),
    _backend(
        "orca", "ORCA", "quantum",
        ("calculate_energy", "calculate_hessian", "optimize_geometry", "calculate_dipole_moment"),
        "User-provided licensed ORCA executable; ResearchChemBench never downloads it.",
        executables=("orca",), environment=("CHEMGRAPH_ORCA_COMMAND",),
        license_class="manual_license", install_notes="Download ORCA from the official portal and set CHEMGRAPH_ORCA_COMMAND.",
        required_methods={action: ("method", "basis") for action in ("calculate_energy", "calculate_hessian", "optimize_geometry", "calculate_dipole_moment")},
        required_settings={
            "optimize_geometry": ("optimization_convergence", "max_steps"),
        },
    ),
    _backend(
        "ase_emt", "ASE EMT", "core", ("calculate_energy", "calculate_forces", "calculate_hessian", "optimize_geometry"),
        "ASE bundled EMT reference calculator, mainly for validation and small supported element sets.",
        modules=("ase.calculators.emt",), pip=("ase",), required_settings={
            "calculate_hessian": ("displacement_angstrom",),
            "optimize_geometry": ("fmax_ev_per_angstrom", "optimizer", "max_steps"),
        },
    ),
    _backend(
        "internal_vibrations", "ResearchChem vibrational analysis", "core", ("derive_vibrational_modes",),
        "Mass-weighted Hessian diagonalization with explicit units and linearity handling.", modules=("numpy",), pip=("numpy",),
        required_settings={"derive_vibrational_modes": ("linearity",)},
    ),
    _backend(
        "internal_spectroscopy", "ResearchChem spectrum builder", "core", ("derive_ir_spectrum",),
        "Deterministic line/broadened spectrum construction from supplied frequencies and intensities.", modules=("numpy",), pip=("numpy",),
        required_settings={"derive_ir_spectrum": ("broadening", "fwhm_cm1")},
    ),
    _backend(
        "internal_thermochemistry", "ResearchChem statistical thermochemistry", "core", ("derive_thermochemistry",),
        "Ideal-gas rigid-rotor/harmonic-oscillator thermochemistry from supplied results.", modules=("ase", "numpy"), pip=("ase", "numpy"),
        required_settings={"derive_thermochemistry": ("temperature_kelvin", "pressure_pa")},
    ),
    _backend(
        "goodvibes", "GoodVibes", "reaction", ("derive_thermochemistry",),
        "GoodVibes thermochemistry from an explicitly supplied parsed quantum output.", modules=("goodvibes",), executables=("goodvibes",),
        conda=("goodvibes",), required_settings={"derive_thermochemistry": ("temperature_kelvin",)},
    ),
    _backend(
        "pysisyphus", "pysisyphus", "reaction", ("locate_transition_state", "trace_intrinsic_reaction_coordinate"),
        "pysisyphus transition-state and IRC algorithms using explicit endpoint/calculator settings.",
        modules=("pysisyphus",), executables=("pysis",), pip=("pysisyphus==1.0.0",),
        required_methods={"locate_transition_state": ("calculator_backend", "method"), "trace_intrinsic_reaction_coordinate": ("calculator_backend", "method")},
        required_settings={
            "locate_transition_state": ("optimizer", "convergence", "max_cycles"),
            "trace_intrinsic_reaction_coordinate": ("integrator", "step_length", "max_cycles", "forward", "backward"),
        },
    ),
    _backend(
        "cantera", "Cantera", "reaction", ("calculate_chemical_equilibrium", "integrate_reaction_network"),
        "Cantera equilibrium and mechanism-based kinetic integration.", modules=("cantera",), conda=("cantera",),
        required_settings={
            "calculate_chemical_equilibrium": ("temperature_kelvin", "pressure_pa", "equilibrium_mode"),
            "integrate_reaction_network": ("time_end_seconds", "num_points"),
        },
    ),
    _backend(
        "scipy", "SciPy", "reaction", ("integrate_reaction_network",),
        "SciPy integration of an explicitly supplied mass-action network.", modules=("scipy",), pip=("scipy",),
        required_settings={"integrate_reaction_network": ("time_end_seconds", "num_points")},
    ),
    _backend(
        "catmap", "CatMAP", "reaction", ("solve_microkinetic_model",),
        "CatMAP microkinetic solver through a typed model adapter.", modules=("catmap",),
        pip=("git+https://github.com/SUNCAT-Center/catmap.git",),
        required_settings={"solve_microkinetic_model": ("temperature_kelvin", "pressure_bar")},
    ),
    _backend(
        "openmm", "OpenMM", "md", ("minimize_system_energy", "propagate_dynamics"),
        "OpenMM minimization and one-segment dynamics propagation.", modules=("openmm",), conda=("openmm",),
        required_settings={
            "minimize_system_energy": ("force_tolerance_kj_mol_nm", "max_iterations"),
            "propagate_dynamics": ("ensemble", "temperature_kelvin", "timestep_fs", "steps", "report_interval"),
        },
    ),
    _backend(
        "gromacs", "GROMACS", "md", ("minimize_system_energy", "propagate_dynamics"),
        "GROMACS execution from typed ParameterizedSystem artifacts and explicit segment settings.",
        executables=("gmx",), environment=("CHEMGRAPH_GROMACS_COMMAND",), conda=("gromacs",),
        required_settings={
            "minimize_system_energy": ("force_tolerance_kj_mol_nm", "max_iterations"),
            "propagate_dynamics": ("ensemble", "temperature_kelvin", "timestep_fs", "steps", "report_interval"),
        },
    ),
    _backend(
        "lammps", "LAMMPS", "md", ("minimize_system_energy", "propagate_dynamics"),
        "LAMMPS execution from typed ParameterizedSystem artifacts and explicit segment settings.",
        modules=("lammps",), executables=("lmp",), environment=("CHEMGRAPH_LAMMPS_COMMAND",), conda=("lammps",),
        required_settings={
            "minimize_system_energy": ("energy_tolerance", "force_tolerance", "max_iterations"),
            "propagate_dynamics": ("ensemble", "temperature_kelvin", "timestep_fs", "steps", "report_interval"),
        },
    ),
    _backend(
        "mdanalysis", "MDAnalysis", "md",
        ("calculate_trajectory_rmsd", "calculate_radius_of_gyration", "calculate_radial_distribution", "calculate_mean_squared_displacement"),
        "Trajectory analysis with explicit atom selections and analysis parameters.", modules=("MDAnalysis",), pip=("MDAnalysis",),
        required_settings={
            "calculate_trajectory_rmsd": ("selection",),
            "calculate_radius_of_gyration": ("selection",),
            "calculate_radial_distribution": ("selection_a", "selection_b", "range_angstrom", "bins"),
            "calculate_mean_squared_displacement": ("selection", "dimensions"),
        },
    ),
    _backend(
        "plumed", "PLUMED", "md", ("evaluate_collective_variables",),
        "PLUMED driver evaluation of supplied collective-variable definitions.", executables=("plumed",),
        environment=("CHEMGRAPH_PLUMED_COMMAND",), conda=("plumed",),
    ),
    _backend(
        "quantum_espresso", "Quantum ESPRESSO", "qe",
        ("calculate_periodic_energy", "calculate_periodic_forces", "calculate_periodic_stress", "relax_periodic_structure"),
        "Quantum ESPRESSO pw.x periodic calculations rendered from typed structures/settings.",
        executables=("pw.x",), environment=("CHEMGRAPH_QE_COMMAND",), conda=("qe",),
        data_resources=(
            "Explicit ResourceRefs from qe_sssp_1_3_pbe_efficiency or qe_sssp_1_3_pbe_precision, one per element; workspace ArtifactRefs remain accepted",
        ),
        method_schema={
            "pseudopotentials": "element -> resource://<SSSP resource id>/<Element> or workspace ArtifactRef",
            "input_dft": "explicit Quantum ESPRESSO XC identifier compatible with the selected resources",
            "ecutwfc_ry": "explicit wavefunction cutoff in Ry; SSSP per-element recommendations are exposed in the resource catalog",
            "ecutrho_ry": "optional explicit charge-density cutoff in Ry",
            "k_points": "{grid:[nx,ny,nz], shift:[sx,sy,sz]}",
        },
        required_methods={action: ("input_dft", "pseudopotentials", "ecutwfc_ry", "k_points") for action in ("calculate_periodic_energy", "calculate_periodic_forces", "calculate_periodic_stress", "relax_periodic_structure")},
        required_settings=_PERIODIC_RELAX,
    ),
    _backend(
        "cp2k", "CP2K", "cp2k",
        ("calculate_periodic_energy", "calculate_periodic_forces", "calculate_periodic_stress", "relax_periodic_structure"),
        "CP2K periodic calculations rendered from typed structures/settings.", executables=("cp2k",),
        environment=("CHEMGRAPH_CP2K_COMMAND",), conda=("cp2k",),
        required_methods={action: ("method", "basis_set", "potential", "cutoff_ry", "k_points", "scf_algorithm") for action in ("calculate_periodic_energy", "calculate_periodic_forces", "calculate_periodic_stress", "relax_periodic_structure")},
        required_settings=_PERIODIC_RELAX,
    ),
    _backend(
        "siesta", "SIESTA", "periodic",
        ("calculate_periodic_energy", "calculate_periodic_forces", "relax_periodic_structure"),
        "SIESTA calculations rendered from typed structures/settings.", executables=("siesta",),
        environment=("CHEMGRAPH_SIESTA_COMMAND",), conda=("siesta",),
        data_resources=(
            "Explicit ResourceRefs from siesta_pseudo_dojo_nc_sr_05_pbe_standard_psml, one per element; workspace ArtifactRefs remain accepted",
        ),
        method_schema={
            "pseudopotentials": "element -> resource://siesta_pseudo_dojo_nc_sr_05_pbe_standard_psml/<Element>",
            "xc_functional": "explicit SIESTA XC family compatible with selected PSML files",
            "xc_authors": "explicit SIESTA XC parametrization",
            "basis_size": "explicit PAO basis size",
            "mesh_cutoff_ry": "explicit real-space mesh cutoff in Ry",
            "k_points": "{grid:[nx,ny,nz], shift:[sx,sy,sz]}",
        },
        required_methods={action: ("xc_functional", "xc_authors", "pseudopotentials", "basis_size", "mesh_cutoff_ry", "k_points") for action in ("calculate_periodic_energy", "calculate_periodic_forces", "relax_periodic_structure")},
        required_settings=_PERIODIC_RELAX,
    ),
    _backend(
        "dftbplus", "DFTB+", "periodic",
        ("calculate_periodic_energy", "calculate_periodic_forces", "relax_periodic_structure"),
        "DFTB+ calculations rendered from typed structures/settings.", executables=("dftb+",),
        environment=("CHEMGRAPH_DFTBPLUS_COMMAND",), conda=("dftbplus",),
        data_resources=(
            "Explicit ResourceRef to dftb_3ob_3_1 or dftb_matsci_0_3 with all required directed element-pair SKF files; workspace directory ArtifactRefs remain accepted",
        ),
        method_schema={
            "parameter_set": "resource://dftb_3ob_3_1 or resource://dftb_matsci_0_3",
            "k_points": "{grid:[nx,ny,nz], shift:[sx,sy,sz]}",
            "scc": "explicit boolean selecting SCC or non-SCC DFTB",
            "max_angular_momenta": "element -> s|p|d|f, explicitly selected for the parameter family",
            "third_order_full": "optional explicit DFTB3 full third-order toggle",
            "hubbard_derivatives": "optional element -> atomic Hubbard derivative mapping",
            "damp_xh_exponent": "optional explicit gamma^h damping exponent (3ob commonly documents 4.0)",
            "fermi_temperature_kelvin": "optional explicit electronic filling temperature",
        },
        required_methods={action: ("parameter_set", "k_points", "scc", "max_angular_momenta") for action in ("calculate_periodic_energy", "calculate_periodic_forces", "relax_periodic_structure")},
        required_settings=_DFTB_SETTINGS,
    ),
    _backend(
        "abinit", "ABINIT", "abinit",
        ("calculate_periodic_energy", "calculate_periodic_forces", "calculate_periodic_stress", "relax_periodic_structure"),
        "ABINIT calculations rendered from typed structures/settings.",
        modules=("numpy", "pydantic", "yaml"), executables=("abinit",),
        environment=("CHEMGRAPH_ABINIT_COMMAND",), conda=("abinit",),
        data_resources=(
            "Explicit ResourceRefs from abinit_pseudo_dojo_nc_sr_pbe_standard_psp8, one per element; workspace ArtifactRefs remain accepted",
        ),
        method_schema={
            "pseudopotentials": "element -> resource://abinit_pseudo_dojo_nc_sr_pbe_standard_psp8/<Element>",
            "ixc": "explicit ABINIT XC code compatible with the selected PSP8 files",
            "ecut_hartree": "explicit plane-wave cutoff in Hartree",
            "k_points": "{grid:[nx,ny,nz], shift:[sx,sy,sz]}",
        },
        required_methods={action: ("ixc", "pseudopotentials", "ecut_hartree", "k_points") for action in ("calculate_periodic_energy", "calculate_periodic_forces", "calculate_periodic_stress", "relax_periodic_structure")},
        required_settings=_PERIODIC_RELAX,
    ),
    _backend(
        "phonopy", "Phonopy", "phonons",
        ("generate_displaced_supercells", "assemble_force_constants", "calculate_phonon_dispersion", "calculate_phonon_density_of_states"),
        "Second-order lattice-dynamics operations on explicit displacement/force artifacts.", modules=("phonopy",),
        executables=("phonopy",), conda=("phonopy",),
        required_settings={
            "generate_displaced_supercells": ("supercell_matrix", "displacement_distance_angstrom"),
            "calculate_phonon_dispersion": ("q_path",),
            "calculate_phonon_density_of_states": ("q_mesh",),
        },
    ),
    _backend(
        "phono3py", "Phono3py", "phonons",
        ("generate_displaced_supercells", "assemble_force_constants", "calculate_phonon_dispersion", "calculate_phonon_density_of_states"),
        "Third-order-capable lattice-dynamics operations on explicit displacement/force artifacts.", modules=("phono3py",),
        executables=("phono3py",), conda=("phono3py",),
        required_settings={
            "generate_displaced_supercells": ("supercell_matrix", "displacement_distance_angstrom", "order"),
            "calculate_phonon_dispersion": ("q_path",),
            "calculate_phonon_density_of_states": ("q_mesh",),
        },
    ),
    _backend(
        "vina", "AutoDock Vina", "docking", ("dock_ligand",),
        "AutoDock Vina docking using prepared structures and an explicit search box.", modules=("vina",),
        executables=("vina",), environment=("CHEMGRAPH_VINA_COMMAND",), conda=("vina",),
        required_settings={"dock_ligand": ("exhaustiveness", "num_modes", "energy_range_kcal_mol")},
    ),
    _backend(
        "gnina", "GNINA", "docking", ("dock_ligand",),
        "GNINA docking using prepared structures and an explicit search box/model.", executables=("gnina",),
        environment=("CHEMGRAPH_GNINA_COMMAND",),
        install_notes="Configured from registered GNINA 1.3.3 CUDA 12.8 binary; rerun scripts/configure_toolbox_resources.py to verify/relink.",
        method_schema={
            "cnn_model": "builtin_default or an explicit GNINA built-in --cnn model name",
            "cnn_scoring": "optional GNINA mode: none|rescore|refinement|metrorescore|metrorefine|all",
            "scoring_function": "optional explicit empirical scoring function",
        },
        required_methods={"dock_ligand": ("cnn_model",)},
        required_settings={"dock_ligand": ("exhaustiveness", "num_modes", "use_gpu")},
    ),
    _backend(
        "pubchem", "PubChem PUG REST", "services", ("search_compounds",),
        "PubChem compound lookup through PubChemPy/PUG REST.", modules=("pubchempy",), pip=("pubchempy==1.0.5",),
    ),
    _backend(
        "rcsb_pdb", "RCSB PDB Data API", "services", ("search_protein_structures",),
        "RCSB PDB entry/search APIs.", modules=("httpx",), pip=("httpx>=0.28",),
    ),
    _backend(
        "materials_project", "Materials Project", "services", ("search_materials",),
        "Materials Project summary REST API requiring an MP_API_KEY for live access; bounded HTTP timeouts avoid unbounded client initialization.", modules=("httpx", "mp_api"),
        environment=("MP_API_KEY",), conda=("mp-api",),
    ),
    _backend(
        "catalysis_hub", "Catalysis-Hub GraphQL", "services", ("search_catalysis_records",),
        "Catalysis-Hub GraphQL reaction lookup.", modules=("httpx",), pip=("httpx>=0.28",),
    ),
)
